// Code generated by client-gen; DO NOT EDIT.

package wdk

import (
	"context"
)

type WalletStorageBasic interface {
	// Migrate migrates a wallet storage database.
	// @Write
	Migrate(ctx context.Context, storageName string, storageIdentityKey string) (string, error)
	// MakeAvailable makes the storage available storage for user.
	// @Write
	MakeAvailable(ctx context.Context) (*TableSettings, error)
	// FindOrInsertUser retrieves an existing user or inserts a new one based on the given identity key.
	// @Write
	FindOrInsertUser(ctx context.Context, identityKey string) (*FindOrInsertUserResponse, error)
	// InternalizeAction handles the internalization of a transaction from the outside of the wallet.
	// @Write
	InternalizeAction(ctx context.Context, args InternalizeActionArgs) (*InternalizeActionResult, error)
	// CreateAction creates a new transaction ready to be signed and processed later.
	// @Write
	CreateAction(ctx context.Context, args ValidCreateActionArgs) (*StorageCreateActionResult, error)
	// ProcessAction processes a signed transaction created by CreateAction.
	// @Write
	ProcessAction(ctx context.Context, args ProcessActionArgs) (*ProcessActionResult, error)
	// InsertCertificateAuth adds a new certificate for a user.
	// @Write
	InsertCertificateAuth(ctx context.Context, certificate *TableCertificateX) (uint, error)
	// RelinquishCertificate revokes the specified certificate from the users certificates.
	// @Write
	RelinquishCertificate(ctx context.Context, args RelinquishCertificateArgs) error
	// ListCertificates retrieves a paginated list of certificates based on the provided filter and pagination arguments.
	// @Read
	ListCertificates(ctx context.Context, args ListCertificatesArgs) (*ListCertificatesResult, error)
	// ListOutputs retrieves a list of wallet outputs based on the provided query parameters in the arguments.
	// @Read
	ListOutputs(ctx context.Context, args ListOutputsArgs) (*ListOutputsResult, error)
	// ListActions retrieves a list of wallet actions based on the provided query parameters in the arguments.
	// @Read
	ListActions(ctx context.Context, args ListActionsArgs) (*ListActionsResult, error)
}
