services:
  jaeger:
    image: jaegertracing/all-in-one:1.35
    profiles: ["tracing"]
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - OTEL_EXPORTER_OTLP_INSECURE=true

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=storage
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local
