bsv_network: main
commission:
    pub_key_hex: ""
    satoshis: 0
db:
    engine: sqlite
    max_connection_idle_time: 6m0s
    max_connection_time: 1m0s
    max_idle_connections: 5
    max_open_connections: 5
    mysql:
        db_name: storage
        host: localhost
        password: ""
        port: "3306"
        protocol: tcp
        time_zone: UTC
        user: root
    postgresql:
        db_name: storage
        host: localhost
        password: postgres
        port: "5432"
        ssl_mode: disable
        time_zone: UTC
        user: postgres
    sqlite:
        connection_string: ./storage.sqlite
fee_model:
    type: sat/kb
    value: 1
http:
    port: 8100
logging:
    enabled: true
    handler: json
    level: info
name: go-storage-server
server_private_key: ""
wallet_services:
    arc:
        callback_token: ""
        callback_url: ""
        deployment_id: ""
        token: mainnet_9596de07e92300c6287e4393594ae39c
        url: https://api.taal.com/arc
        wait_for: ""
    bitails_api_key: null
    chaintracks: null
    chaintracks_fiat_exchange_rates_url: ""
    disable_mapi_callback: true
    exchangerates_api_key: bd539d2ff492bcb5619d5f27726a766f
    fiat_exchange_rates:
        base: USD
        rates:
            EUR: 0.93
            GBP: 0.8
            USD: 1
        timestamp: {}
    fiat_update_interval: 24h0m0s
    whats_on_chain:
        api_key: ""
        bsv_exchange_rate:
            base: USD
            rates: 47.52
            timestamp: {}
        bsv_update_interval: 15m0s
