package generator

import (
	"bytes"
	"embed"
	"go/format"
	"log"
	"slices"
	"text/template"

	"github.com/bsv-blockchain/go-wallet-toolbox/tools/client-gen/extractor"
	"github.com/bsv-blockchain/go-wallet-toolbox/tools/client-gen/metadata"
	"github.com/go-softwarelab/common/pkg/is"
	"github.com/go-softwarelab/common/pkg/seq"
	slicesx "github.com/go-softwarelab/common/pkg/slices"
)

//go:embed templates
var goCodeTemplates embed.FS

// TemplateData holds information required to generate code, including package details, interfaces, and imports.
type TemplateData struct {
	Package    *metadata.Package
	Interfaces []extractor.InterfaceInfo
	Imports    []extractor.Import
}

// Data generates template data for a package, filtering methods and collecting unique imports from the given interfaces.
func Data(pkg *metadata.Package, interfaces []extractor.InterfaceInfo, methodsToSkip []string) TemplateData {
	allImports := seq.FlattenSlices(seq.Map(seq.FromSlice(interfaces), func(i extractor.InterfaceInfo) []extractor.Import {
		return i.Imports
	}))
	allImports = seq.UniqBy(allImports, func(i extractor.Import) string {
		return i.Path
	})

	interfaces = slicesx.Map(interfaces, func(i extractor.InterfaceInfo) extractor.InterfaceInfo {
		i.Methods = slicesx.Filter(i.Methods, func(method metadata.MethodInfo) bool {
			return !slices.Contains(methodsToSkip, method.Name)
		})
		return i
	})

	return TemplateData{
		Package:    pkg,
		Interfaces: interfaces,
		Imports:    seq.Collect(allImports),
	}
}

// Generate will generate client code and embed client.tpl file with it
func Generate(data TemplateData, templateFile string) []byte {
	templateFile = "templates/" + templateFile

	tmplContent, err := goCodeTemplates.ReadFile(templateFile)
	if err != nil {
		log.Fatalf("Failed to read template %s: %v", templateFile, err)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by client-gen; DO NOT EDIT.\n\n")

	// Generate Go code using the template
	tmpl, err := template.New("gocode").
		Funcs(template.FuncMap{
			"printType": data.Package.PrintType,
			"contains":  slices.Contains[[]string, string],
			"coalesce":  coalesce,
			"strings":   strings,
		}).
		Parse(string(tmplContent))
	if err != nil {
		log.Fatalf("Failed to parse template: %v", err)
	}

	err = tmpl.Execute(&buf, data)
	if err != nil {
		log.Fatalf("Failed to execute template: %v", err)
	}

	// Format the generated code
	formattedCode, err := format.Source(buf.Bytes())
	if err != nil {
		log.Println("Result\n", buf.String())
		log.Fatalf("Failed to format generated code: %v", err)
	}

	return formattedCode
}

func coalesce(values ...any) any {
	for _, value := range values {
		if is.NotEmpty(value) {
			return value
		}
	}
	return nil
}

func strings(values ...string) []string {
	return values
}
