package modelgen

import (
	"bytes"
	"github.com/go-softwarelab/common/pkg/seq"
	"go/format"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"log"
	"maps"
	"os"
	"path/filepath"
	"text/template"
	"time"
)

// outputTemplate is the template for the generated Go file.
const outputTemplate = `// Code generated by gorm-names-gen. DO NOT EDIT.
// Generated at: {{.Timestamp}}
//
// To regenerate this file, run "go generate" in the models directory.

package {{.PackageName}}

{{range .Models}}
var {{.Name}}ColumnNames = struct {
	{{- range .Fields}}
    {{.GoName}} string
	{{- end}}
}{
    {{- range .Fields}}
    {{.GoName}}: "{{.DBName}}",
    {{- end}}
}
{{end}}
`

// ModelData holds the processed information for a single GORM model.
type ModelData struct {
	Name   string      // The name of the struct, e.g., "Commission"
	Fields []FieldData // A slice of fields in the struct
}

// FieldData holds information about a single field.
type FieldData struct {
	GoName string // The Go field name, e.g., "TransactionID"
	DBName string // The database column name, e.g., "transaction_id"
}

// Generate uses a GORM DB instance to generate the field name structs.
//
//   - db: An initialized GORM DB instance (e.g., connected to in-memory SQLite).
//   - modelsToGenerate: A map where keys are the Go struct names and values are instances
//     of the models (e.g., map[string]interface{}{"Commission": &Commission{}}).
//   - outputPath: The directory where the generated file should be saved.
//   - outputFilename: The name of the generated file (e.g., "models_generated.go").
//   - packageName: The package name for the generated file (e.g., "models").
func Generate(modelsToGenerate map[string]interface{}, outputPath, outputFilename, packageName string) {
	db, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{})
	if err != nil {
		log.Fatalf("failed to connect database: %v", err)
	}

	err = db.AutoMigrate(seq.Collect(maps.Values(modelsToGenerate))...)
	if err != nil {
		log.Fatalf("failed to perform automigrate: %v", err)
	}

	log.SetFlags(0)
	log.SetPrefix("modelgen: ")

	allModels := make([]ModelData, 0, len(modelsToGenerate))

	// --- 1. Get Column Names using db.Migrator() ---
	for name, modelInstance := range modelsToGenerate {
		// Use the migrator to get column types
		columnTypes, err := db.Migrator().ColumnTypes(modelInstance)
		if err != nil {
			log.Fatalf("failed to get column types for model %s: %v", name, err)
		}

		model := ModelData{Name: name}
		for _, col := range columnTypes {
			// GORM's migrator gives us the DB name. We need to find the corresponding Go field name.
			// This is a bit tricky, but we can use GORM's schema parser for this mapping.
			stmt := &gorm.Statement{DB: db}
			if err = stmt.Parse(modelInstance); err != nil {
				log.Fatalf("failed to parse model %s: %v", name, err)
			}

			field := stmt.Schema.LookUpField(col.Name())

			if field != nil {
				model.Fields = append(model.Fields, FieldData{
					GoName: field.Name,
					DBName: col.Name(),
				})
			}
		}
		allModels = append(allModels, model)
	}

	// --- 2. Code Generation using Template ---
	tmpl, err := template.New("models").Parse(outputTemplate)
	if err != nil {
		log.Fatalf("failed to parse template: %v", err)
	}

	var buf bytes.Buffer
	templateData := map[string]interface{}{
		"Timestamp":   time.Now().Format(time.RFC1123),
		"PackageName": packageName,
		"Models":      allModels,
	}

	if err := tmpl.Execute(&buf, templateData); err != nil {
		log.Fatalf("failed to execute template: %v", err)
	}

	// --- 3. Formatting and Writing the Output ---
	formattedSource, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("failed to format generated code: %v\nSource:\n%s", err, buf.String())
	}

	fullOutputPath := filepath.Join(outputPath, outputFilename)
	err = os.WriteFile(fullOutputPath, formattedSource, 0600)
	if err != nil {
		log.Fatalf("failed to write output file: %v", err)
	}

	log.Printf("successfully generated %s", fullOutputPath)
}
