// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package genquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Commission      *commission
	KnownTx         *knownTx
	NumericIDLookup *numericIDLookup
	OutputBasket    *outputBasket
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Commission = &Q.Commission
	KnownTx = &Q.KnownTx
	NumericIDLookup = &Q.NumericIDLookup
	OutputBasket = &Q.OutputBasket
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Commission:      newCommission(db, opts...),
		KnownTx:         newKnownTx(db, opts...),
		NumericIDLookup: newNumericIDLookup(db, opts...),
		OutputBasket:    newOutputBasket(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Commission      commission
	KnownTx         knownTx
	NumericIDLookup numericIDLookup
	OutputBasket    outputBasket
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Commission:      q.Commission.clone(db),
		KnownTx:         q.KnownTx.clone(db),
		NumericIDLookup: q.NumericIDLookup.clone(db),
		OutputBasket:    q.OutputBasket.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Commission:      q.Commission.replaceDB(db),
		KnownTx:         q.KnownTx.replaceDB(db),
		NumericIDLookup: q.NumericIDLookup.replaceDB(db),
		OutputBasket:    q.OutputBasket.replaceDB(db),
	}
}

type queryCtx struct {
	Commission      ICommissionDo
	KnownTx         IKnownTxDo
	NumericIDLookup INumericIDLookupDo
	OutputBasket    IOutputBasketDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Commission:      q.Commission.WithContext(ctx),
		KnownTx:         q.KnownTx.WithContext(ctx),
		NumericIDLookup: q.NumericIDLookup.WithContext(ctx),
		OutputBasket:    q.OutputBasket.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
