// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package genquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	Commission       *commission
	KnownTx          *knownTx
	Label            *label
	NumericIDLookup  *numericIDLookup
	Output           *output
	OutputBasket     *outputBasket
	Transaction      *transaction
	TransactionLabel *transactionLabel
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Commission = &Q.Commission
	KnownTx = &Q.KnownTx
	Label = &Q.Label
	NumericIDLookup = &Q.NumericIDLookup
	Output = &Q.Output
	OutputBasket = &Q.OutputBasket
	Transaction = &Q.Transaction
	TransactionLabel = &Q.TransactionLabel
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		Commission:       newCommission(db, opts...),
		KnownTx:          newKnownTx(db, opts...),
		Label:            newLabel(db, opts...),
		NumericIDLookup:  newNumericIDLookup(db, opts...),
		Output:           newOutput(db, opts...),
		OutputBasket:     newOutputBasket(db, opts...),
		Transaction:      newTransaction(db, opts...),
		TransactionLabel: newTransactionLabel(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Commission       commission
	KnownTx          knownTx
	Label            label
	NumericIDLookup  numericIDLookup
	Output           output
	OutputBasket     outputBasket
	Transaction      transaction
	TransactionLabel transactionLabel
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Commission:       q.Commission.clone(db),
		KnownTx:          q.KnownTx.clone(db),
		Label:            q.Label.clone(db),
		NumericIDLookup:  q.NumericIDLookup.clone(db),
		Output:           q.Output.clone(db),
		OutputBasket:     q.OutputBasket.clone(db),
		Transaction:      q.Transaction.clone(db),
		TransactionLabel: q.TransactionLabel.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Commission:       q.Commission.replaceDB(db),
		KnownTx:          q.KnownTx.replaceDB(db),
		Label:            q.Label.replaceDB(db),
		NumericIDLookup:  q.NumericIDLookup.replaceDB(db),
		Output:           q.Output.replaceDB(db),
		OutputBasket:     q.OutputBasket.replaceDB(db),
		Transaction:      q.Transaction.replaceDB(db),
		TransactionLabel: q.TransactionLabel.replaceDB(db),
	}
}

type queryCtx struct {
	Commission       ICommissionDo
	KnownTx          IKnownTxDo
	Label            ILabelDo
	NumericIDLookup  INumericIDLookupDo
	Output           IOutputDo
	OutputBasket     IOutputBasketDo
	Transaction      ITransactionDo
	TransactionLabel ITransactionLabelDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Commission:       q.Commission.WithContext(ctx),
		KnownTx:          q.KnownTx.WithContext(ctx),
		Label:            q.Label.WithContext(ctx),
		NumericIDLookup:  q.NumericIDLookup.WithContext(ctx),
		Output:           q.Output.WithContext(ctx),
		OutputBasket:     q.OutputBasket.WithContext(ctx),
		Transaction:      q.Transaction.WithContext(ctx),
		TransactionLabel: q.TransactionLabel.WithContext(ctx),
	}
}

func (q *Query) DBTransaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
