// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package genquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                    db,
		Certificate:           newCertificate(db, opts...),
		ChaintracksBulkFile:   newChaintracksBulkFile(db, opts...),
		ChaintracksLiveHeader: newChaintracksLiveHeader(db, opts...),
		Commission:            newCommission(db, opts...),
		MonitorEvent:          newMonitorEvent(db, opts...),
		Output:                newOutput(db, opts...),
		OutputBasket:          newOutputBasket(db, opts...),
		OutputTag:             newOutputTag(db, opts...),
		OutputTagsMap:         newOutputTagsMap(db, opts...),
		ProvenTx:              newProvenTx(db, opts...),
		ProvenTxReq:           newProvenTxReq(db, opts...),
		Transaction:           newTransaction(db, opts...),
		TxLabel:               newTxLabel(db, opts...),
		TxLabelsMap:           newTxLabelsMap(db, opts...),
		User:                  newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Certificate           certificate
	ChaintracksBulkFile   chaintracksBulkFile
	ChaintracksLiveHeader chaintracksLiveHeader
	Commission            commission
	MonitorEvent          monitorEvent
	Output                output
	OutputBasket          outputBasket
	OutputTag             outputTag
	OutputTagsMap         outputTagsMap
	ProvenTx              provenTx
	ProvenTxReq           provenTxReq
	Transaction           transaction
	TxLabel               txLabel
	TxLabelsMap           txLabelsMap
	User                  user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Certificate:           q.Certificate.clone(db),
		ChaintracksBulkFile:   q.ChaintracksBulkFile.clone(db),
		ChaintracksLiveHeader: q.ChaintracksLiveHeader.clone(db),
		Commission:            q.Commission.clone(db),
		MonitorEvent:          q.MonitorEvent.clone(db),
		Output:                q.Output.clone(db),
		OutputBasket:          q.OutputBasket.clone(db),
		OutputTag:             q.OutputTag.clone(db),
		OutputTagsMap:         q.OutputTagsMap.clone(db),
		ProvenTx:              q.ProvenTx.clone(db),
		ProvenTxReq:           q.ProvenTxReq.clone(db),
		Transaction:           q.Transaction.clone(db),
		TxLabel:               q.TxLabel.clone(db),
		TxLabelsMap:           q.TxLabelsMap.clone(db),
		User:                  q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Certificate:           q.Certificate.replaceDB(db),
		ChaintracksBulkFile:   q.ChaintracksBulkFile.replaceDB(db),
		ChaintracksLiveHeader: q.ChaintracksLiveHeader.replaceDB(db),
		Commission:            q.Commission.replaceDB(db),
		MonitorEvent:          q.MonitorEvent.replaceDB(db),
		Output:                q.Output.replaceDB(db),
		OutputBasket:          q.OutputBasket.replaceDB(db),
		OutputTag:             q.OutputTag.replaceDB(db),
		OutputTagsMap:         q.OutputTagsMap.replaceDB(db),
		ProvenTx:              q.ProvenTx.replaceDB(db),
		ProvenTxReq:           q.ProvenTxReq.replaceDB(db),
		Transaction:           q.Transaction.replaceDB(db),
		TxLabel:               q.TxLabel.replaceDB(db),
		TxLabelsMap:           q.TxLabelsMap.replaceDB(db),
		User:                  q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Certificate           ICertificateDo
	ChaintracksBulkFile   IChaintracksBulkFileDo
	ChaintracksLiveHeader IChaintracksLiveHeaderDo
	Commission            ICommissionDo
	MonitorEvent          IMonitorEventDo
	Output                IOutputDo
	OutputBasket          IOutputBasketDo
	OutputTag             IOutputTagDo
	OutputTagsMap         IOutputTagsMapDo
	ProvenTx              IProvenTxDo
	ProvenTxReq           IProvenTxReqDo
	Transaction           ITransactionDo
	TxLabel               ITxLabelDo
	TxLabelsMap           ITxLabelsMapDo
	User                  IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Certificate:           q.Certificate.WithContext(ctx),
		ChaintracksBulkFile:   q.ChaintracksBulkFile.WithContext(ctx),
		ChaintracksLiveHeader: q.ChaintracksLiveHeader.WithContext(ctx),
		Commission:            q.Commission.WithContext(ctx),
		MonitorEvent:          q.MonitorEvent.WithContext(ctx),
		Output:                q.Output.WithContext(ctx),
		OutputBasket:          q.OutputBasket.WithContext(ctx),
		OutputTag:             q.OutputTag.WithContext(ctx),
		OutputTagsMap:         q.OutputTagsMap.WithContext(ctx),
		ProvenTx:              q.ProvenTx.WithContext(ctx),
		ProvenTxReq:           q.ProvenTxReq.WithContext(ctx),
		Transaction:           q.Transaction.WithContext(ctx),
		TxLabel:               q.TxLabel.WithContext(ctx),
		TxLabelsMap:           q.TxLabelsMap.WithContext(ctx),
		User:                  q.User.WithContext(ctx),
	}
}

func (q *Query) DBTransaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
