// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package genquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bsv-blockchain/go-wallet-toolbox/pkg/internal/storage/database/models"
)

func newMonitorEvent(db *gorm.DB, opts ...gen.DOOption) monitorEvent {
	_monitorEvent := monitorEvent{}

	_monitorEvent.monitorEventDo.UseDB(db, opts...)
	_monitorEvent.monitorEventDo.UseModel(&models.MonitorEvent{})

	tableName := _monitorEvent.monitorEventDo.TableName()
	_monitorEvent.ALL = field.NewAsterisk(tableName)
	_monitorEvent.CreatedAt = field.NewTime(tableName, "created_at")
	_monitorEvent.UpdatedAt = field.NewTime(tableName, "updated_at")
	_monitorEvent.ID = field.NewUint(tableName, "id")
	_monitorEvent.Event = field.NewString(tableName, "event")
	_monitorEvent.Details = field.NewString(tableName, "details")

	_monitorEvent.fillFieldMap()

	return _monitorEvent
}

type monitorEvent struct {
	monitorEventDo

	ALL       field.Asterisk
	CreatedAt field.Time
	UpdatedAt field.Time
	ID        field.Uint
	Event     field.String
	Details   field.String

	fieldMap map[string]field.Expr
}

func (m monitorEvent) Table(newTableName string) *monitorEvent {
	m.monitorEventDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m monitorEvent) As(alias string) *monitorEvent {
	m.monitorEventDo.DO = *(m.monitorEventDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *monitorEvent) updateTableName(table string) *monitorEvent {
	m.ALL = field.NewAsterisk(table)
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.ID = field.NewUint(table, "id")
	m.Event = field.NewString(table, "event")
	m.Details = field.NewString(table, "details")

	m.fillFieldMap()

	return m
}

func (m *monitorEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *monitorEvent) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["id"] = m.ID
	m.fieldMap["event"] = m.Event
	m.fieldMap["details"] = m.Details
}

func (m monitorEvent) clone(db *gorm.DB) monitorEvent {
	m.monitorEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m monitorEvent) replaceDB(db *gorm.DB) monitorEvent {
	m.monitorEventDo.ReplaceDB(db)
	return m
}

type monitorEventDo struct{ gen.DO }

type IMonitorEventDo interface {
	gen.SubQuery
	Debug() IMonitorEventDo
	WithContext(ctx context.Context) IMonitorEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMonitorEventDo
	WriteDB() IMonitorEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMonitorEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMonitorEventDo
	Not(conds ...gen.Condition) IMonitorEventDo
	Or(conds ...gen.Condition) IMonitorEventDo
	Select(conds ...field.Expr) IMonitorEventDo
	Where(conds ...gen.Condition) IMonitorEventDo
	Order(conds ...field.Expr) IMonitorEventDo
	Distinct(cols ...field.Expr) IMonitorEventDo
	Omit(cols ...field.Expr) IMonitorEventDo
	Join(table schema.Tabler, on ...field.Expr) IMonitorEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMonitorEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMonitorEventDo
	Group(cols ...field.Expr) IMonitorEventDo
	Having(conds ...gen.Condition) IMonitorEventDo
	Limit(limit int) IMonitorEventDo
	Offset(offset int) IMonitorEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMonitorEventDo
	Unscoped() IMonitorEventDo
	Create(values ...*models.MonitorEvent) error
	CreateInBatches(values []*models.MonitorEvent, batchSize int) error
	Save(values ...*models.MonitorEvent) error
	First() (*models.MonitorEvent, error)
	Take() (*models.MonitorEvent, error)
	Last() (*models.MonitorEvent, error)
	Find() ([]*models.MonitorEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MonitorEvent, err error)
	FindInBatches(result *[]*models.MonitorEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MonitorEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMonitorEventDo
	Assign(attrs ...field.AssignExpr) IMonitorEventDo
	Joins(fields ...field.RelationField) IMonitorEventDo
	Preload(fields ...field.RelationField) IMonitorEventDo
	FirstOrInit() (*models.MonitorEvent, error)
	FirstOrCreate() (*models.MonitorEvent, error)
	FindByPage(offset int, limit int) (result []*models.MonitorEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMonitorEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m monitorEventDo) Debug() IMonitorEventDo {
	return m.withDO(m.DO.Debug())
}

func (m monitorEventDo) WithContext(ctx context.Context) IMonitorEventDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m monitorEventDo) ReadDB() IMonitorEventDo {
	return m.Clauses(dbresolver.Read)
}

func (m monitorEventDo) WriteDB() IMonitorEventDo {
	return m.Clauses(dbresolver.Write)
}

func (m monitorEventDo) Session(config *gorm.Session) IMonitorEventDo {
	return m.withDO(m.DO.Session(config))
}

func (m monitorEventDo) Clauses(conds ...clause.Expression) IMonitorEventDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m monitorEventDo) Returning(value interface{}, columns ...string) IMonitorEventDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m monitorEventDo) Not(conds ...gen.Condition) IMonitorEventDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m monitorEventDo) Or(conds ...gen.Condition) IMonitorEventDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m monitorEventDo) Select(conds ...field.Expr) IMonitorEventDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m monitorEventDo) Where(conds ...gen.Condition) IMonitorEventDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m monitorEventDo) Order(conds ...field.Expr) IMonitorEventDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m monitorEventDo) Distinct(cols ...field.Expr) IMonitorEventDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m monitorEventDo) Omit(cols ...field.Expr) IMonitorEventDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m monitorEventDo) Join(table schema.Tabler, on ...field.Expr) IMonitorEventDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m monitorEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMonitorEventDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m monitorEventDo) RightJoin(table schema.Tabler, on ...field.Expr) IMonitorEventDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m monitorEventDo) Group(cols ...field.Expr) IMonitorEventDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m monitorEventDo) Having(conds ...gen.Condition) IMonitorEventDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m monitorEventDo) Limit(limit int) IMonitorEventDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m monitorEventDo) Offset(offset int) IMonitorEventDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m monitorEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMonitorEventDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m monitorEventDo) Unscoped() IMonitorEventDo {
	return m.withDO(m.DO.Unscoped())
}

func (m monitorEventDo) Create(values ...*models.MonitorEvent) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m monitorEventDo) CreateInBatches(values []*models.MonitorEvent, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m monitorEventDo) Save(values ...*models.MonitorEvent) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m monitorEventDo) First() (*models.MonitorEvent, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MonitorEvent), nil
	}
}

func (m monitorEventDo) Take() (*models.MonitorEvent, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MonitorEvent), nil
	}
}

func (m monitorEventDo) Last() (*models.MonitorEvent, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MonitorEvent), nil
	}
}

func (m monitorEventDo) Find() ([]*models.MonitorEvent, error) {
	result, err := m.DO.Find()
	return result.([]*models.MonitorEvent), err
}

func (m monitorEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MonitorEvent, err error) {
	buf := make([]*models.MonitorEvent, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m monitorEventDo) FindInBatches(result *[]*models.MonitorEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m monitorEventDo) Attrs(attrs ...field.AssignExpr) IMonitorEventDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m monitorEventDo) Assign(attrs ...field.AssignExpr) IMonitorEventDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m monitorEventDo) Joins(fields ...field.RelationField) IMonitorEventDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m monitorEventDo) Preload(fields ...field.RelationField) IMonitorEventDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m monitorEventDo) FirstOrInit() (*models.MonitorEvent, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MonitorEvent), nil
	}
}

func (m monitorEventDo) FirstOrCreate() (*models.MonitorEvent, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MonitorEvent), nil
	}
}

func (m monitorEventDo) FindByPage(offset int, limit int) (result []*models.MonitorEvent, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m monitorEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m monitorEventDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m monitorEventDo) Delete(models ...*models.MonitorEvent) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *monitorEventDo) withDO(do gen.Dao) *monitorEventDo {
	m.DO = *do.(*gen.DO)
	return m
}
