// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package genquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bsv-blockchain/go-wallet-toolbox/pkg/internal/storage/database/models"
)

func newOutputTagsMap(db *gorm.DB, opts ...gen.DOOption) outputTagsMap {
	_outputTagsMap := outputTagsMap{}

	_outputTagsMap.outputTagsMapDo.UseDB(db, opts...)
	_outputTagsMap.outputTagsMapDo.UseModel(&models.OutputTagsMap{})

	tableName := _outputTagsMap.outputTagsMapDo.TableName()
	_outputTagsMap.ALL = field.NewAsterisk(tableName)
	_outputTagsMap.CreatedAt = field.NewTime(tableName, "created_at")
	_outputTagsMap.UpdatedAt = field.NewTime(tableName, "updated_at")
	_outputTagsMap.OutputTagID = field.NewInt(tableName, "outputTagId")
	_outputTagsMap.OutputID = field.NewInt(tableName, "outputId")
	_outputTagsMap.IsDeleted = field.NewBool(tableName, "isDeleted")

	_outputTagsMap.fillFieldMap()

	return _outputTagsMap
}

type outputTagsMap struct {
	outputTagsMapDo

	ALL         field.Asterisk
	CreatedAt   field.Time
	UpdatedAt   field.Time
	OutputTagID field.Int
	OutputID    field.Int
	IsDeleted   field.Bool

	fieldMap map[string]field.Expr
}

func (o outputTagsMap) Table(newTableName string) *outputTagsMap {
	o.outputTagsMapDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o outputTagsMap) As(alias string) *outputTagsMap {
	o.outputTagsMapDo.DO = *(o.outputTagsMapDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *outputTagsMap) updateTableName(table string) *outputTagsMap {
	o.ALL = field.NewAsterisk(table)
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.OutputTagID = field.NewInt(table, "outputTagId")
	o.OutputID = field.NewInt(table, "outputId")
	o.IsDeleted = field.NewBool(table, "isDeleted")

	o.fillFieldMap()

	return o
}

func (o *outputTagsMap) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *outputTagsMap) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 5)
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["outputTagId"] = o.OutputTagID
	o.fieldMap["outputId"] = o.OutputID
	o.fieldMap["isDeleted"] = o.IsDeleted
}

func (o outputTagsMap) clone(db *gorm.DB) outputTagsMap {
	o.outputTagsMapDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o outputTagsMap) replaceDB(db *gorm.DB) outputTagsMap {
	o.outputTagsMapDo.ReplaceDB(db)
	return o
}

type outputTagsMapDo struct{ gen.DO }

type IOutputTagsMapDo interface {
	gen.SubQuery
	Debug() IOutputTagsMapDo
	WithContext(ctx context.Context) IOutputTagsMapDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOutputTagsMapDo
	WriteDB() IOutputTagsMapDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOutputTagsMapDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOutputTagsMapDo
	Not(conds ...gen.Condition) IOutputTagsMapDo
	Or(conds ...gen.Condition) IOutputTagsMapDo
	Select(conds ...field.Expr) IOutputTagsMapDo
	Where(conds ...gen.Condition) IOutputTagsMapDo
	Order(conds ...field.Expr) IOutputTagsMapDo
	Distinct(cols ...field.Expr) IOutputTagsMapDo
	Omit(cols ...field.Expr) IOutputTagsMapDo
	Join(table schema.Tabler, on ...field.Expr) IOutputTagsMapDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOutputTagsMapDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOutputTagsMapDo
	Group(cols ...field.Expr) IOutputTagsMapDo
	Having(conds ...gen.Condition) IOutputTagsMapDo
	Limit(limit int) IOutputTagsMapDo
	Offset(offset int) IOutputTagsMapDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOutputTagsMapDo
	Unscoped() IOutputTagsMapDo
	Create(values ...*models.OutputTagsMap) error
	CreateInBatches(values []*models.OutputTagsMap, batchSize int) error
	Save(values ...*models.OutputTagsMap) error
	First() (*models.OutputTagsMap, error)
	Take() (*models.OutputTagsMap, error)
	Last() (*models.OutputTagsMap, error)
	Find() ([]*models.OutputTagsMap, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.OutputTagsMap, err error)
	FindInBatches(result *[]*models.OutputTagsMap, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.OutputTagsMap) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOutputTagsMapDo
	Assign(attrs ...field.AssignExpr) IOutputTagsMapDo
	Joins(fields ...field.RelationField) IOutputTagsMapDo
	Preload(fields ...field.RelationField) IOutputTagsMapDo
	FirstOrInit() (*models.OutputTagsMap, error)
	FirstOrCreate() (*models.OutputTagsMap, error)
	FindByPage(offset int, limit int) (result []*models.OutputTagsMap, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOutputTagsMapDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o outputTagsMapDo) Debug() IOutputTagsMapDo {
	return o.withDO(o.DO.Debug())
}

func (o outputTagsMapDo) WithContext(ctx context.Context) IOutputTagsMapDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o outputTagsMapDo) ReadDB() IOutputTagsMapDo {
	return o.Clauses(dbresolver.Read)
}

func (o outputTagsMapDo) WriteDB() IOutputTagsMapDo {
	return o.Clauses(dbresolver.Write)
}

func (o outputTagsMapDo) Session(config *gorm.Session) IOutputTagsMapDo {
	return o.withDO(o.DO.Session(config))
}

func (o outputTagsMapDo) Clauses(conds ...clause.Expression) IOutputTagsMapDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o outputTagsMapDo) Returning(value interface{}, columns ...string) IOutputTagsMapDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o outputTagsMapDo) Not(conds ...gen.Condition) IOutputTagsMapDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o outputTagsMapDo) Or(conds ...gen.Condition) IOutputTagsMapDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o outputTagsMapDo) Select(conds ...field.Expr) IOutputTagsMapDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o outputTagsMapDo) Where(conds ...gen.Condition) IOutputTagsMapDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o outputTagsMapDo) Order(conds ...field.Expr) IOutputTagsMapDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o outputTagsMapDo) Distinct(cols ...field.Expr) IOutputTagsMapDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o outputTagsMapDo) Omit(cols ...field.Expr) IOutputTagsMapDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o outputTagsMapDo) Join(table schema.Tabler, on ...field.Expr) IOutputTagsMapDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o outputTagsMapDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOutputTagsMapDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o outputTagsMapDo) RightJoin(table schema.Tabler, on ...field.Expr) IOutputTagsMapDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o outputTagsMapDo) Group(cols ...field.Expr) IOutputTagsMapDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o outputTagsMapDo) Having(conds ...gen.Condition) IOutputTagsMapDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o outputTagsMapDo) Limit(limit int) IOutputTagsMapDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o outputTagsMapDo) Offset(offset int) IOutputTagsMapDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o outputTagsMapDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOutputTagsMapDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o outputTagsMapDo) Unscoped() IOutputTagsMapDo {
	return o.withDO(o.DO.Unscoped())
}

func (o outputTagsMapDo) Create(values ...*models.OutputTagsMap) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o outputTagsMapDo) CreateInBatches(values []*models.OutputTagsMap, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o outputTagsMapDo) Save(values ...*models.OutputTagsMap) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o outputTagsMapDo) First() (*models.OutputTagsMap, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.OutputTagsMap), nil
	}
}

func (o outputTagsMapDo) Take() (*models.OutputTagsMap, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.OutputTagsMap), nil
	}
}

func (o outputTagsMapDo) Last() (*models.OutputTagsMap, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.OutputTagsMap), nil
	}
}

func (o outputTagsMapDo) Find() ([]*models.OutputTagsMap, error) {
	result, err := o.DO.Find()
	return result.([]*models.OutputTagsMap), err
}

func (o outputTagsMapDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.OutputTagsMap, err error) {
	buf := make([]*models.OutputTagsMap, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o outputTagsMapDo) FindInBatches(result *[]*models.OutputTagsMap, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o outputTagsMapDo) Attrs(attrs ...field.AssignExpr) IOutputTagsMapDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o outputTagsMapDo) Assign(attrs ...field.AssignExpr) IOutputTagsMapDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o outputTagsMapDo) Joins(fields ...field.RelationField) IOutputTagsMapDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o outputTagsMapDo) Preload(fields ...field.RelationField) IOutputTagsMapDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o outputTagsMapDo) FirstOrInit() (*models.OutputTagsMap, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.OutputTagsMap), nil
	}
}

func (o outputTagsMapDo) FirstOrCreate() (*models.OutputTagsMap, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.OutputTagsMap), nil
	}
}

func (o outputTagsMapDo) FindByPage(offset int, limit int) (result []*models.OutputTagsMap, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o outputTagsMapDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o outputTagsMapDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o outputTagsMapDo) Delete(models ...*models.OutputTagsMap) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *outputTagsMapDo) withDO(do gen.Dao) *outputTagsMapDo {
	o.DO = *do.(*gen.DO)
	return o
}
