// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package genquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bsv-blockchain/go-wallet-toolbox/pkg/internal/storage/database/models"
)

func newProvenTxReq(db *gorm.DB, opts ...gen.DOOption) provenTxReq {
	_provenTxReq := provenTxReq{}

	_provenTxReq.provenTxReqDo.UseDB(db, opts...)
	_provenTxReq.provenTxReqDo.UseModel(&models.ProvenTxReq{})

	tableName := _provenTxReq.provenTxReqDo.TableName()
	_provenTxReq.ALL = field.NewAsterisk(tableName)
	_provenTxReq.CreatedAt = field.NewTime(tableName, "created_at")
	_provenTxReq.UpdatedAt = field.NewTime(tableName, "updated_at")
	_provenTxReq.ProvenTxReqID = field.NewUint(tableName, "provenTxReqId")
	_provenTxReq.ProvenTxID = field.NewUint(tableName, "provenTxId")
	_provenTxReq.Status = field.NewString(tableName, "status")
	_provenTxReq.Attempts = field.NewUint64(tableName, "attempts")
	_provenTxReq.RebroadcastAttempts = field.NewInt(tableName, "rebroadcastAttempts")
	_provenTxReq.Notified = field.NewBool(tableName, "notified")
	_provenTxReq.Batch = field.NewString(tableName, "batch")
	_provenTxReq.WasBroadcast = field.NewBool(tableName, "wasBroadcast")
	_provenTxReq.TxID = field.NewString(tableName, "txid")
	_provenTxReq.RawTx = field.NewBytes(tableName, "rawTx")
	_provenTxReq.InputBeef = field.NewBytes(tableName, "inputBeef")
	_provenTxReq.History = field.NewString(tableName, "history")
	_provenTxReq.Notify = field.NewString(tableName, "notify")
	_provenTxReq.ProvenTx = provenTxReqHasOneProvenTx{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ProvenTx", "models.ProvenTx"),
	}

	_provenTxReq.fillFieldMap()

	return _provenTxReq
}

type provenTxReq struct {
	provenTxReqDo

	ALL                 field.Asterisk
	CreatedAt           field.Time
	UpdatedAt           field.Time
	ProvenTxReqID       field.Uint
	ProvenTxID          field.Uint
	Status              field.String
	Attempts            field.Uint64
	RebroadcastAttempts field.Int
	Notified            field.Bool
	Batch               field.String
	WasBroadcast        field.Bool
	TxID                field.String
	RawTx               field.Bytes
	InputBeef           field.Bytes
	History             field.String
	Notify              field.String
	ProvenTx            provenTxReqHasOneProvenTx

	fieldMap map[string]field.Expr
}

func (p provenTxReq) Table(newTableName string) *provenTxReq {
	p.provenTxReqDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p provenTxReq) As(alias string) *provenTxReq {
	p.provenTxReqDo.DO = *(p.provenTxReqDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *provenTxReq) updateTableName(table string) *provenTxReq {
	p.ALL = field.NewAsterisk(table)
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.ProvenTxReqID = field.NewUint(table, "provenTxReqId")
	p.ProvenTxID = field.NewUint(table, "provenTxId")
	p.Status = field.NewString(table, "status")
	p.Attempts = field.NewUint64(table, "attempts")
	p.RebroadcastAttempts = field.NewInt(table, "rebroadcastAttempts")
	p.Notified = field.NewBool(table, "notified")
	p.Batch = field.NewString(table, "batch")
	p.WasBroadcast = field.NewBool(table, "wasBroadcast")
	p.TxID = field.NewString(table, "txid")
	p.RawTx = field.NewBytes(table, "rawTx")
	p.InputBeef = field.NewBytes(table, "inputBeef")
	p.History = field.NewString(table, "history")
	p.Notify = field.NewString(table, "notify")

	p.fillFieldMap()

	return p
}

func (p *provenTxReq) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *provenTxReq) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 16)
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["provenTxReqId"] = p.ProvenTxReqID
	p.fieldMap["provenTxId"] = p.ProvenTxID
	p.fieldMap["status"] = p.Status
	p.fieldMap["attempts"] = p.Attempts
	p.fieldMap["rebroadcastAttempts"] = p.RebroadcastAttempts
	p.fieldMap["notified"] = p.Notified
	p.fieldMap["batch"] = p.Batch
	p.fieldMap["wasBroadcast"] = p.WasBroadcast
	p.fieldMap["txid"] = p.TxID
	p.fieldMap["rawTx"] = p.RawTx
	p.fieldMap["inputBeef"] = p.InputBeef
	p.fieldMap["history"] = p.History
	p.fieldMap["notify"] = p.Notify

}

func (p provenTxReq) clone(db *gorm.DB) provenTxReq {
	p.provenTxReqDo.ReplaceConnPool(db.Statement.ConnPool)
	p.ProvenTx.db = db.Session(&gorm.Session{Initialized: true})
	p.ProvenTx.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p provenTxReq) replaceDB(db *gorm.DB) provenTxReq {
	p.provenTxReqDo.ReplaceDB(db)
	p.ProvenTx.db = db.Session(&gorm.Session{})
	return p
}

type provenTxReqHasOneProvenTx struct {
	db *gorm.DB

	field.RelationField
}

func (a provenTxReqHasOneProvenTx) Where(conds ...field.Expr) *provenTxReqHasOneProvenTx {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a provenTxReqHasOneProvenTx) WithContext(ctx context.Context) *provenTxReqHasOneProvenTx {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a provenTxReqHasOneProvenTx) Session(session *gorm.Session) *provenTxReqHasOneProvenTx {
	a.db = a.db.Session(session)
	return &a
}

func (a provenTxReqHasOneProvenTx) Model(m *models.ProvenTxReq) *provenTxReqHasOneProvenTxTx {
	return &provenTxReqHasOneProvenTxTx{a.db.Model(m).Association(a.Name())}
}

func (a provenTxReqHasOneProvenTx) Unscoped() *provenTxReqHasOneProvenTx {
	a.db = a.db.Unscoped()
	return &a
}

type provenTxReqHasOneProvenTxTx struct{ tx *gorm.Association }

func (a provenTxReqHasOneProvenTxTx) Find() (result *models.ProvenTx, err error) {
	return result, a.tx.Find(&result)
}

func (a provenTxReqHasOneProvenTxTx) Append(values ...*models.ProvenTx) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a provenTxReqHasOneProvenTxTx) Replace(values ...*models.ProvenTx) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a provenTxReqHasOneProvenTxTx) Delete(values ...*models.ProvenTx) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a provenTxReqHasOneProvenTxTx) Clear() error {
	return a.tx.Clear()
}

func (a provenTxReqHasOneProvenTxTx) Count() int64 {
	return a.tx.Count()
}

func (a provenTxReqHasOneProvenTxTx) Unscoped() *provenTxReqHasOneProvenTxTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type provenTxReqDo struct{ gen.DO }

type IProvenTxReqDo interface {
	gen.SubQuery
	Debug() IProvenTxReqDo
	WithContext(ctx context.Context) IProvenTxReqDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProvenTxReqDo
	WriteDB() IProvenTxReqDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProvenTxReqDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProvenTxReqDo
	Not(conds ...gen.Condition) IProvenTxReqDo
	Or(conds ...gen.Condition) IProvenTxReqDo
	Select(conds ...field.Expr) IProvenTxReqDo
	Where(conds ...gen.Condition) IProvenTxReqDo
	Order(conds ...field.Expr) IProvenTxReqDo
	Distinct(cols ...field.Expr) IProvenTxReqDo
	Omit(cols ...field.Expr) IProvenTxReqDo
	Join(table schema.Tabler, on ...field.Expr) IProvenTxReqDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProvenTxReqDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProvenTxReqDo
	Group(cols ...field.Expr) IProvenTxReqDo
	Having(conds ...gen.Condition) IProvenTxReqDo
	Limit(limit int) IProvenTxReqDo
	Offset(offset int) IProvenTxReqDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProvenTxReqDo
	Unscoped() IProvenTxReqDo
	Create(values ...*models.ProvenTxReq) error
	CreateInBatches(values []*models.ProvenTxReq, batchSize int) error
	Save(values ...*models.ProvenTxReq) error
	First() (*models.ProvenTxReq, error)
	Take() (*models.ProvenTxReq, error)
	Last() (*models.ProvenTxReq, error)
	Find() ([]*models.ProvenTxReq, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ProvenTxReq, err error)
	FindInBatches(result *[]*models.ProvenTxReq, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ProvenTxReq) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProvenTxReqDo
	Assign(attrs ...field.AssignExpr) IProvenTxReqDo
	Joins(fields ...field.RelationField) IProvenTxReqDo
	Preload(fields ...field.RelationField) IProvenTxReqDo
	FirstOrInit() (*models.ProvenTxReq, error)
	FirstOrCreate() (*models.ProvenTxReq, error)
	FindByPage(offset int, limit int) (result []*models.ProvenTxReq, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProvenTxReqDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p provenTxReqDo) Debug() IProvenTxReqDo {
	return p.withDO(p.DO.Debug())
}

func (p provenTxReqDo) WithContext(ctx context.Context) IProvenTxReqDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p provenTxReqDo) ReadDB() IProvenTxReqDo {
	return p.Clauses(dbresolver.Read)
}

func (p provenTxReqDo) WriteDB() IProvenTxReqDo {
	return p.Clauses(dbresolver.Write)
}

func (p provenTxReqDo) Session(config *gorm.Session) IProvenTxReqDo {
	return p.withDO(p.DO.Session(config))
}

func (p provenTxReqDo) Clauses(conds ...clause.Expression) IProvenTxReqDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p provenTxReqDo) Returning(value interface{}, columns ...string) IProvenTxReqDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p provenTxReqDo) Not(conds ...gen.Condition) IProvenTxReqDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p provenTxReqDo) Or(conds ...gen.Condition) IProvenTxReqDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p provenTxReqDo) Select(conds ...field.Expr) IProvenTxReqDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p provenTxReqDo) Where(conds ...gen.Condition) IProvenTxReqDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p provenTxReqDo) Order(conds ...field.Expr) IProvenTxReqDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p provenTxReqDo) Distinct(cols ...field.Expr) IProvenTxReqDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p provenTxReqDo) Omit(cols ...field.Expr) IProvenTxReqDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p provenTxReqDo) Join(table schema.Tabler, on ...field.Expr) IProvenTxReqDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p provenTxReqDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProvenTxReqDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p provenTxReqDo) RightJoin(table schema.Tabler, on ...field.Expr) IProvenTxReqDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p provenTxReqDo) Group(cols ...field.Expr) IProvenTxReqDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p provenTxReqDo) Having(conds ...gen.Condition) IProvenTxReqDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p provenTxReqDo) Limit(limit int) IProvenTxReqDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p provenTxReqDo) Offset(offset int) IProvenTxReqDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p provenTxReqDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProvenTxReqDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p provenTxReqDo) Unscoped() IProvenTxReqDo {
	return p.withDO(p.DO.Unscoped())
}

func (p provenTxReqDo) Create(values ...*models.ProvenTxReq) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p provenTxReqDo) CreateInBatches(values []*models.ProvenTxReq, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p provenTxReqDo) Save(values ...*models.ProvenTxReq) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p provenTxReqDo) First() (*models.ProvenTxReq, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProvenTxReq), nil
	}
}

func (p provenTxReqDo) Take() (*models.ProvenTxReq, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProvenTxReq), nil
	}
}

func (p provenTxReqDo) Last() (*models.ProvenTxReq, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProvenTxReq), nil
	}
}

func (p provenTxReqDo) Find() ([]*models.ProvenTxReq, error) {
	result, err := p.DO.Find()
	return result.([]*models.ProvenTxReq), err
}

func (p provenTxReqDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ProvenTxReq, err error) {
	buf := make([]*models.ProvenTxReq, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p provenTxReqDo) FindInBatches(result *[]*models.ProvenTxReq, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p provenTxReqDo) Attrs(attrs ...field.AssignExpr) IProvenTxReqDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p provenTxReqDo) Assign(attrs ...field.AssignExpr) IProvenTxReqDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p provenTxReqDo) Joins(fields ...field.RelationField) IProvenTxReqDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p provenTxReqDo) Preload(fields ...field.RelationField) IProvenTxReqDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p provenTxReqDo) FirstOrInit() (*models.ProvenTxReq, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProvenTxReq), nil
	}
}

func (p provenTxReqDo) FirstOrCreate() (*models.ProvenTxReq, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProvenTxReq), nil
	}
}

func (p provenTxReqDo) FindByPage(offset int, limit int) (result []*models.ProvenTxReq, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p provenTxReqDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p provenTxReqDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p provenTxReqDo) Delete(models ...*models.ProvenTxReq) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *provenTxReqDo) withDO(do gen.Dao) *provenTxReqDo {
	p.DO = *do.(*gen.DO)
	return p
}
