// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package genquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bsv-blockchain/go-wallet-toolbox/pkg/internal/storage/database/models"
)

func newProvenTx(db *gorm.DB, opts ...gen.DOOption) provenTx {
	_provenTx := provenTx{}

	_provenTx.provenTxDo.UseDB(db, opts...)
	_provenTx.provenTxDo.UseModel(&models.ProvenTx{})

	tableName := _provenTx.provenTxDo.TableName()
	_provenTx.ALL = field.NewAsterisk(tableName)
	_provenTx.CreatedAt = field.NewTime(tableName, "created_at")
	_provenTx.UpdatedAt = field.NewTime(tableName, "updated_at")
	_provenTx.ProvenTxID = field.NewUint(tableName, "provenTxId")
	_provenTx.TxID = field.NewString(tableName, "txid")
	_provenTx.Height = field.NewUint32(tableName, "height")
	_provenTx.Index = field.NewUint64(tableName, "index")
	_provenTx.MerklePath = field.NewBytes(tableName, "merklePath")
	_provenTx.RawTx = field.NewBytes(tableName, "rawTx")
	_provenTx.BlockHash = field.NewString(tableName, "blockHash")
	_provenTx.MerkleRoot = field.NewString(tableName, "merkleRoot")

	_provenTx.fillFieldMap()

	return _provenTx
}

type provenTx struct {
	provenTxDo

	ALL        field.Asterisk
	CreatedAt  field.Time
	UpdatedAt  field.Time
	ProvenTxID field.Uint
	TxID       field.String
	Height     field.Uint32
	Index      field.Uint64
	MerklePath field.Bytes
	RawTx      field.Bytes
	BlockHash  field.String
	MerkleRoot field.String

	fieldMap map[string]field.Expr
}

func (p provenTx) Table(newTableName string) *provenTx {
	p.provenTxDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p provenTx) As(alias string) *provenTx {
	p.provenTxDo.DO = *(p.provenTxDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *provenTx) updateTableName(table string) *provenTx {
	p.ALL = field.NewAsterisk(table)
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.ProvenTxID = field.NewUint(table, "provenTxId")
	p.TxID = field.NewString(table, "txid")
	p.Height = field.NewUint32(table, "height")
	p.Index = field.NewUint64(table, "index")
	p.MerklePath = field.NewBytes(table, "merklePath")
	p.RawTx = field.NewBytes(table, "rawTx")
	p.BlockHash = field.NewString(table, "blockHash")
	p.MerkleRoot = field.NewString(table, "merkleRoot")

	p.fillFieldMap()

	return p
}

func (p *provenTx) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *provenTx) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 10)
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["provenTxId"] = p.ProvenTxID
	p.fieldMap["txid"] = p.TxID
	p.fieldMap["height"] = p.Height
	p.fieldMap["index"] = p.Index
	p.fieldMap["merklePath"] = p.MerklePath
	p.fieldMap["rawTx"] = p.RawTx
	p.fieldMap["blockHash"] = p.BlockHash
	p.fieldMap["merkleRoot"] = p.MerkleRoot
}

func (p provenTx) clone(db *gorm.DB) provenTx {
	p.provenTxDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p provenTx) replaceDB(db *gorm.DB) provenTx {
	p.provenTxDo.ReplaceDB(db)
	return p
}

type provenTxDo struct{ gen.DO }

type IProvenTxDo interface {
	gen.SubQuery
	Debug() IProvenTxDo
	WithContext(ctx context.Context) IProvenTxDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProvenTxDo
	WriteDB() IProvenTxDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProvenTxDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProvenTxDo
	Not(conds ...gen.Condition) IProvenTxDo
	Or(conds ...gen.Condition) IProvenTxDo
	Select(conds ...field.Expr) IProvenTxDo
	Where(conds ...gen.Condition) IProvenTxDo
	Order(conds ...field.Expr) IProvenTxDo
	Distinct(cols ...field.Expr) IProvenTxDo
	Omit(cols ...field.Expr) IProvenTxDo
	Join(table schema.Tabler, on ...field.Expr) IProvenTxDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProvenTxDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProvenTxDo
	Group(cols ...field.Expr) IProvenTxDo
	Having(conds ...gen.Condition) IProvenTxDo
	Limit(limit int) IProvenTxDo
	Offset(offset int) IProvenTxDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProvenTxDo
	Unscoped() IProvenTxDo
	Create(values ...*models.ProvenTx) error
	CreateInBatches(values []*models.ProvenTx, batchSize int) error
	Save(values ...*models.ProvenTx) error
	First() (*models.ProvenTx, error)
	Take() (*models.ProvenTx, error)
	Last() (*models.ProvenTx, error)
	Find() ([]*models.ProvenTx, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ProvenTx, err error)
	FindInBatches(result *[]*models.ProvenTx, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ProvenTx) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProvenTxDo
	Assign(attrs ...field.AssignExpr) IProvenTxDo
	Joins(fields ...field.RelationField) IProvenTxDo
	Preload(fields ...field.RelationField) IProvenTxDo
	FirstOrInit() (*models.ProvenTx, error)
	FirstOrCreate() (*models.ProvenTx, error)
	FindByPage(offset int, limit int) (result []*models.ProvenTx, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProvenTxDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p provenTxDo) Debug() IProvenTxDo {
	return p.withDO(p.DO.Debug())
}

func (p provenTxDo) WithContext(ctx context.Context) IProvenTxDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p provenTxDo) ReadDB() IProvenTxDo {
	return p.Clauses(dbresolver.Read)
}

func (p provenTxDo) WriteDB() IProvenTxDo {
	return p.Clauses(dbresolver.Write)
}

func (p provenTxDo) Session(config *gorm.Session) IProvenTxDo {
	return p.withDO(p.DO.Session(config))
}

func (p provenTxDo) Clauses(conds ...clause.Expression) IProvenTxDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p provenTxDo) Returning(value interface{}, columns ...string) IProvenTxDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p provenTxDo) Not(conds ...gen.Condition) IProvenTxDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p provenTxDo) Or(conds ...gen.Condition) IProvenTxDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p provenTxDo) Select(conds ...field.Expr) IProvenTxDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p provenTxDo) Where(conds ...gen.Condition) IProvenTxDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p provenTxDo) Order(conds ...field.Expr) IProvenTxDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p provenTxDo) Distinct(cols ...field.Expr) IProvenTxDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p provenTxDo) Omit(cols ...field.Expr) IProvenTxDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p provenTxDo) Join(table schema.Tabler, on ...field.Expr) IProvenTxDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p provenTxDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProvenTxDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p provenTxDo) RightJoin(table schema.Tabler, on ...field.Expr) IProvenTxDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p provenTxDo) Group(cols ...field.Expr) IProvenTxDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p provenTxDo) Having(conds ...gen.Condition) IProvenTxDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p provenTxDo) Limit(limit int) IProvenTxDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p provenTxDo) Offset(offset int) IProvenTxDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p provenTxDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProvenTxDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p provenTxDo) Unscoped() IProvenTxDo {
	return p.withDO(p.DO.Unscoped())
}

func (p provenTxDo) Create(values ...*models.ProvenTx) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p provenTxDo) CreateInBatches(values []*models.ProvenTx, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p provenTxDo) Save(values ...*models.ProvenTx) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p provenTxDo) First() (*models.ProvenTx, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProvenTx), nil
	}
}

func (p provenTxDo) Take() (*models.ProvenTx, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProvenTx), nil
	}
}

func (p provenTxDo) Last() (*models.ProvenTx, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProvenTx), nil
	}
}

func (p provenTxDo) Find() ([]*models.ProvenTx, error) {
	result, err := p.DO.Find()
	return result.([]*models.ProvenTx), err
}

func (p provenTxDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ProvenTx, err error) {
	buf := make([]*models.ProvenTx, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p provenTxDo) FindInBatches(result *[]*models.ProvenTx, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p provenTxDo) Attrs(attrs ...field.AssignExpr) IProvenTxDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p provenTxDo) Assign(attrs ...field.AssignExpr) IProvenTxDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p provenTxDo) Joins(fields ...field.RelationField) IProvenTxDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p provenTxDo) Preload(fields ...field.RelationField) IProvenTxDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p provenTxDo) FirstOrInit() (*models.ProvenTx, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProvenTx), nil
	}
}

func (p provenTxDo) FirstOrCreate() (*models.ProvenTx, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProvenTx), nil
	}
}

func (p provenTxDo) FindByPage(offset int, limit int) (result []*models.ProvenTx, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p provenTxDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p provenTxDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p provenTxDo) Delete(models ...*models.ProvenTx) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *provenTxDo) withDO(do gen.Dao) *provenTxDo {
	p.DO = *do.(*gen.DO)
	return p
}
