// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package genquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bsv-blockchain/go-wallet-toolbox/pkg/internal/storage/database/models"
)

func newTransaction(db *gorm.DB, opts ...gen.DOOption) transaction {
	_transaction := transaction{}

	_transaction.transactionDo.UseDB(db, opts...)
	_transaction.transactionDo.UseModel(&models.Transaction{})

	tableName := _transaction.transactionDo.TableName()
	_transaction.ALL = field.NewAsterisk(tableName)
	_transaction.CreatedAt = field.NewTime(tableName, "created_at")
	_transaction.UpdatedAt = field.NewTime(tableName, "updated_at")
	_transaction.TransactionID = field.NewUint(tableName, "transactionId")
	_transaction.UserID = field.NewInt(tableName, "userId")
	_transaction.Status = field.NewString(tableName, "status")
	_transaction.Reference = field.NewString(tableName, "reference")
	_transaction.IsOutgoing = field.NewBool(tableName, "isOutgoing")
	_transaction.Satoshis = field.NewInt64(tableName, "satoshis")
	_transaction.Description = field.NewString(tableName, "description")
	_transaction.Version = field.NewUint32(tableName, "version")
	_transaction.LockTime = field.NewUint32(tableName, "lockTime")
	_transaction.TxID = field.NewString(tableName, "txid")
	_transaction.InputBeef = field.NewBytes(tableName, "inputBeef")
	_transaction.ProvenTxID = field.NewUint(tableName, "provenTxId")
	_transaction.RawTx = field.NewBytes(tableName, "rawTx")
	_transaction.Commission = transactionHasOneCommission{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Commission", "models.Commission"),
	}

	_transaction.ProvenTx = transactionHasOneProvenTx{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ProvenTx", "models.ProvenTx"),
	}

	_transaction.Outputs = transactionHasManyOutputs{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Outputs", "models.Output"),
		SpentByTransaction: struct {
			field.RelationField
			Commission struct {
				field.RelationField
			}
			ProvenTx struct {
				field.RelationField
			}
			Outputs struct {
				field.RelationField
			}
			Inputs struct {
				field.RelationField
			}
			Labels struct {
				field.RelationField
				Transactions struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Outputs.SpentByTransaction", "models.Transaction"),
			Commission: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Outputs.SpentByTransaction.Commission", "models.Commission"),
			},
			ProvenTx: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Outputs.SpentByTransaction.ProvenTx", "models.ProvenTx"),
			},
			Outputs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Outputs.SpentByTransaction.Outputs", "models.Output"),
			},
			Inputs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Outputs.SpentByTransaction.Inputs", "models.Output"),
			},
			Labels: struct {
				field.RelationField
				Transactions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Outputs.SpentByTransaction.Labels", "models.TxLabel"),
				Transactions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Outputs.SpentByTransaction.Labels.Transactions", "models.Transaction"),
				},
			},
		},
		Basket: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Outputs.Basket", "models.OutputBasket"),
		},
		Transaction: struct {
			field.RelationField
			Commission struct {
				field.RelationField
			}
			ProvenTx struct {
				field.RelationField
			}
			Outputs struct {
				field.RelationField
			}
			Inputs struct {
				field.RelationField
			}
			Labels struct {
				field.RelationField
				Transactions struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Outputs.Transaction", "models.Transaction"),
			Commission: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Outputs.Transaction.Commission", "models.Commission"),
			},
			ProvenTx: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Outputs.Transaction.ProvenTx", "models.ProvenTx"),
			},
			Outputs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Outputs.Transaction.Outputs", "models.Output"),
			},
			Inputs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Outputs.Transaction.Inputs", "models.Output"),
			},
			Labels: struct {
				field.RelationField
				Transactions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Outputs.Transaction.Labels", "models.TxLabel"),
				Transactions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Outputs.Transaction.Labels.Transactions", "models.Transaction"),
				},
			},
		},
		Tags: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Outputs.Tags", "models.OutputTag"),
		},
	}

	_transaction.Inputs = transactionHasManyInputs{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Inputs", "models.Output"),
		SpentByTransaction: struct {
			field.RelationField
			Commission struct {
				field.RelationField
			}
			ProvenTx struct {
				field.RelationField
			}
			Outputs struct {
				field.RelationField
			}
			Inputs struct {
				field.RelationField
			}
			Labels struct {
				field.RelationField
				Transactions struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Inputs.SpentByTransaction", "models.Transaction"),
			Commission: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Inputs.SpentByTransaction.Commission", "models.Commission"),
			},
			ProvenTx: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Inputs.SpentByTransaction.ProvenTx", "models.ProvenTx"),
			},
			Outputs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Inputs.SpentByTransaction.Outputs", "models.Output"),
			},
			Inputs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Inputs.SpentByTransaction.Inputs", "models.Output"),
			},
			Labels: struct {
				field.RelationField
				Transactions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Inputs.SpentByTransaction.Labels", "models.TxLabel"),
				Transactions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Inputs.SpentByTransaction.Labels.Transactions", "models.Transaction"),
				},
			},
		},
		Basket: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Inputs.Basket", "models.OutputBasket"),
		},
		Transaction: struct {
			field.RelationField
			Commission struct {
				field.RelationField
			}
			ProvenTx struct {
				field.RelationField
			}
			Outputs struct {
				field.RelationField
			}
			Inputs struct {
				field.RelationField
			}
			Labels struct {
				field.RelationField
				Transactions struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Inputs.Transaction", "models.Transaction"),
			Commission: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Inputs.Transaction.Commission", "models.Commission"),
			},
			ProvenTx: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Inputs.Transaction.ProvenTx", "models.ProvenTx"),
			},
			Outputs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Inputs.Transaction.Outputs", "models.Output"),
			},
			Inputs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Inputs.Transaction.Inputs", "models.Output"),
			},
			Labels: struct {
				field.RelationField
				Transactions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Inputs.Transaction.Labels", "models.TxLabel"),
				Transactions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Inputs.Transaction.Labels.Transactions", "models.Transaction"),
				},
			},
		},
		Tags: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Inputs.Tags", "models.OutputTag"),
		},
	}

	_transaction.Labels = transactionManyToManyLabels{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Labels", "models.TxLabel"),
		Transactions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Labels.Transactions", "models.Transaction"),
		},
	}

	_transaction.fillFieldMap()

	return _transaction
}

type transaction struct {
	transactionDo

	ALL           field.Asterisk
	CreatedAt     field.Time
	UpdatedAt     field.Time
	TransactionID field.Uint
	UserID        field.Int
	Status        field.String
	Reference     field.String
	IsOutgoing    field.Bool
	Satoshis      field.Int64
	Description   field.String
	Version       field.Uint32
	LockTime      field.Uint32
	TxID          field.String
	InputBeef     field.Bytes
	ProvenTxID    field.Uint
	RawTx         field.Bytes
	Commission    transactionHasOneCommission

	ProvenTx transactionHasOneProvenTx

	Outputs transactionHasManyOutputs

	Inputs transactionHasManyInputs

	Labels transactionManyToManyLabels

	fieldMap map[string]field.Expr
}

func (t transaction) Table(newTableName string) *transaction {
	t.transactionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t transaction) As(alias string) *transaction {
	t.transactionDo.DO = *(t.transactionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *transaction) updateTableName(table string) *transaction {
	t.ALL = field.NewAsterisk(table)
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.TransactionID = field.NewUint(table, "transactionId")
	t.UserID = field.NewInt(table, "userId")
	t.Status = field.NewString(table, "status")
	t.Reference = field.NewString(table, "reference")
	t.IsOutgoing = field.NewBool(table, "isOutgoing")
	t.Satoshis = field.NewInt64(table, "satoshis")
	t.Description = field.NewString(table, "description")
	t.Version = field.NewUint32(table, "version")
	t.LockTime = field.NewUint32(table, "lockTime")
	t.TxID = field.NewString(table, "txid")
	t.InputBeef = field.NewBytes(table, "inputBeef")
	t.ProvenTxID = field.NewUint(table, "provenTxId")
	t.RawTx = field.NewBytes(table, "rawTx")

	t.fillFieldMap()

	return t
}

func (t *transaction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *transaction) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 20)
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["transactionId"] = t.TransactionID
	t.fieldMap["userId"] = t.UserID
	t.fieldMap["status"] = t.Status
	t.fieldMap["reference"] = t.Reference
	t.fieldMap["isOutgoing"] = t.IsOutgoing
	t.fieldMap["satoshis"] = t.Satoshis
	t.fieldMap["description"] = t.Description
	t.fieldMap["version"] = t.Version
	t.fieldMap["lockTime"] = t.LockTime
	t.fieldMap["txid"] = t.TxID
	t.fieldMap["inputBeef"] = t.InputBeef
	t.fieldMap["provenTxId"] = t.ProvenTxID
	t.fieldMap["rawTx"] = t.RawTx

}

func (t transaction) clone(db *gorm.DB) transaction {
	t.transactionDo.ReplaceConnPool(db.Statement.ConnPool)
	t.Commission.db = db.Session(&gorm.Session{Initialized: true})
	t.Commission.db.Statement.ConnPool = db.Statement.ConnPool
	t.ProvenTx.db = db.Session(&gorm.Session{Initialized: true})
	t.ProvenTx.db.Statement.ConnPool = db.Statement.ConnPool
	t.Outputs.db = db.Session(&gorm.Session{Initialized: true})
	t.Outputs.db.Statement.ConnPool = db.Statement.ConnPool
	t.Inputs.db = db.Session(&gorm.Session{Initialized: true})
	t.Inputs.db.Statement.ConnPool = db.Statement.ConnPool
	t.Labels.db = db.Session(&gorm.Session{Initialized: true})
	t.Labels.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t transaction) replaceDB(db *gorm.DB) transaction {
	t.transactionDo.ReplaceDB(db)
	t.Commission.db = db.Session(&gorm.Session{})
	t.ProvenTx.db = db.Session(&gorm.Session{})
	t.Outputs.db = db.Session(&gorm.Session{})
	t.Inputs.db = db.Session(&gorm.Session{})
	t.Labels.db = db.Session(&gorm.Session{})
	return t
}

type transactionHasOneCommission struct {
	db *gorm.DB

	field.RelationField
}

func (a transactionHasOneCommission) Where(conds ...field.Expr) *transactionHasOneCommission {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a transactionHasOneCommission) WithContext(ctx context.Context) *transactionHasOneCommission {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a transactionHasOneCommission) Session(session *gorm.Session) *transactionHasOneCommission {
	a.db = a.db.Session(session)
	return &a
}

func (a transactionHasOneCommission) Model(m *models.Transaction) *transactionHasOneCommissionTx {
	return &transactionHasOneCommissionTx{a.db.Model(m).Association(a.Name())}
}

func (a transactionHasOneCommission) Unscoped() *transactionHasOneCommission {
	a.db = a.db.Unscoped()
	return &a
}

type transactionHasOneCommissionTx struct{ tx *gorm.Association }

func (a transactionHasOneCommissionTx) Find() (result *models.Commission, err error) {
	return result, a.tx.Find(&result)
}

func (a transactionHasOneCommissionTx) Append(values ...*models.Commission) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a transactionHasOneCommissionTx) Replace(values ...*models.Commission) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a transactionHasOneCommissionTx) Delete(values ...*models.Commission) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a transactionHasOneCommissionTx) Clear() error {
	return a.tx.Clear()
}

func (a transactionHasOneCommissionTx) Count() int64 {
	return a.tx.Count()
}

func (a transactionHasOneCommissionTx) Unscoped() *transactionHasOneCommissionTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type transactionHasOneProvenTx struct {
	db *gorm.DB

	field.RelationField
}

func (a transactionHasOneProvenTx) Where(conds ...field.Expr) *transactionHasOneProvenTx {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a transactionHasOneProvenTx) WithContext(ctx context.Context) *transactionHasOneProvenTx {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a transactionHasOneProvenTx) Session(session *gorm.Session) *transactionHasOneProvenTx {
	a.db = a.db.Session(session)
	return &a
}

func (a transactionHasOneProvenTx) Model(m *models.Transaction) *transactionHasOneProvenTxTx {
	return &transactionHasOneProvenTxTx{a.db.Model(m).Association(a.Name())}
}

func (a transactionHasOneProvenTx) Unscoped() *transactionHasOneProvenTx {
	a.db = a.db.Unscoped()
	return &a
}

type transactionHasOneProvenTxTx struct{ tx *gorm.Association }

func (a transactionHasOneProvenTxTx) Find() (result *models.ProvenTx, err error) {
	return result, a.tx.Find(&result)
}

func (a transactionHasOneProvenTxTx) Append(values ...*models.ProvenTx) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a transactionHasOneProvenTxTx) Replace(values ...*models.ProvenTx) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a transactionHasOneProvenTxTx) Delete(values ...*models.ProvenTx) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a transactionHasOneProvenTxTx) Clear() error {
	return a.tx.Clear()
}

func (a transactionHasOneProvenTxTx) Count() int64 {
	return a.tx.Count()
}

func (a transactionHasOneProvenTxTx) Unscoped() *transactionHasOneProvenTxTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type transactionHasManyOutputs struct {
	db *gorm.DB

	field.RelationField

	SpentByTransaction struct {
		field.RelationField
		Commission struct {
			field.RelationField
		}
		ProvenTx struct {
			field.RelationField
		}
		Outputs struct {
			field.RelationField
		}
		Inputs struct {
			field.RelationField
		}
		Labels struct {
			field.RelationField
			Transactions struct {
				field.RelationField
			}
		}
	}
	Basket struct {
		field.RelationField
	}
	Transaction struct {
		field.RelationField
		Commission struct {
			field.RelationField
		}
		ProvenTx struct {
			field.RelationField
		}
		Outputs struct {
			field.RelationField
		}
		Inputs struct {
			field.RelationField
		}
		Labels struct {
			field.RelationField
			Transactions struct {
				field.RelationField
			}
		}
	}
	Tags struct {
		field.RelationField
	}
}

func (a transactionHasManyOutputs) Where(conds ...field.Expr) *transactionHasManyOutputs {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a transactionHasManyOutputs) WithContext(ctx context.Context) *transactionHasManyOutputs {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a transactionHasManyOutputs) Session(session *gorm.Session) *transactionHasManyOutputs {
	a.db = a.db.Session(session)
	return &a
}

func (a transactionHasManyOutputs) Model(m *models.Transaction) *transactionHasManyOutputsTx {
	return &transactionHasManyOutputsTx{a.db.Model(m).Association(a.Name())}
}

func (a transactionHasManyOutputs) Unscoped() *transactionHasManyOutputs {
	a.db = a.db.Unscoped()
	return &a
}

type transactionHasManyOutputsTx struct{ tx *gorm.Association }

func (a transactionHasManyOutputsTx) Find() (result []*models.Output, err error) {
	return result, a.tx.Find(&result)
}

func (a transactionHasManyOutputsTx) Append(values ...*models.Output) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a transactionHasManyOutputsTx) Replace(values ...*models.Output) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a transactionHasManyOutputsTx) Delete(values ...*models.Output) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a transactionHasManyOutputsTx) Clear() error {
	return a.tx.Clear()
}

func (a transactionHasManyOutputsTx) Count() int64 {
	return a.tx.Count()
}

func (a transactionHasManyOutputsTx) Unscoped() *transactionHasManyOutputsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type transactionHasManyInputs struct {
	db *gorm.DB

	field.RelationField

	SpentByTransaction struct {
		field.RelationField
		Commission struct {
			field.RelationField
		}
		ProvenTx struct {
			field.RelationField
		}
		Outputs struct {
			field.RelationField
		}
		Inputs struct {
			field.RelationField
		}
		Labels struct {
			field.RelationField
			Transactions struct {
				field.RelationField
			}
		}
	}
	Basket struct {
		field.RelationField
	}
	Transaction struct {
		field.RelationField
		Commission struct {
			field.RelationField
		}
		ProvenTx struct {
			field.RelationField
		}
		Outputs struct {
			field.RelationField
		}
		Inputs struct {
			field.RelationField
		}
		Labels struct {
			field.RelationField
			Transactions struct {
				field.RelationField
			}
		}
	}
	Tags struct {
		field.RelationField
	}
}

func (a transactionHasManyInputs) Where(conds ...field.Expr) *transactionHasManyInputs {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a transactionHasManyInputs) WithContext(ctx context.Context) *transactionHasManyInputs {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a transactionHasManyInputs) Session(session *gorm.Session) *transactionHasManyInputs {
	a.db = a.db.Session(session)
	return &a
}

func (a transactionHasManyInputs) Model(m *models.Transaction) *transactionHasManyInputsTx {
	return &transactionHasManyInputsTx{a.db.Model(m).Association(a.Name())}
}

func (a transactionHasManyInputs) Unscoped() *transactionHasManyInputs {
	a.db = a.db.Unscoped()
	return &a
}

type transactionHasManyInputsTx struct{ tx *gorm.Association }

func (a transactionHasManyInputsTx) Find() (result []*models.Output, err error) {
	return result, a.tx.Find(&result)
}

func (a transactionHasManyInputsTx) Append(values ...*models.Output) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a transactionHasManyInputsTx) Replace(values ...*models.Output) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a transactionHasManyInputsTx) Delete(values ...*models.Output) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a transactionHasManyInputsTx) Clear() error {
	return a.tx.Clear()
}

func (a transactionHasManyInputsTx) Count() int64 {
	return a.tx.Count()
}

func (a transactionHasManyInputsTx) Unscoped() *transactionHasManyInputsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type transactionManyToManyLabels struct {
	db *gorm.DB

	field.RelationField

	Transactions struct {
		field.RelationField
	}
}

func (a transactionManyToManyLabels) Where(conds ...field.Expr) *transactionManyToManyLabels {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a transactionManyToManyLabels) WithContext(ctx context.Context) *transactionManyToManyLabels {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a transactionManyToManyLabels) Session(session *gorm.Session) *transactionManyToManyLabels {
	a.db = a.db.Session(session)
	return &a
}

func (a transactionManyToManyLabels) Model(m *models.Transaction) *transactionManyToManyLabelsTx {
	return &transactionManyToManyLabelsTx{a.db.Model(m).Association(a.Name())}
}

func (a transactionManyToManyLabels) Unscoped() *transactionManyToManyLabels {
	a.db = a.db.Unscoped()
	return &a
}

type transactionManyToManyLabelsTx struct{ tx *gorm.Association }

func (a transactionManyToManyLabelsTx) Find() (result []*models.TxLabel, err error) {
	return result, a.tx.Find(&result)
}

func (a transactionManyToManyLabelsTx) Append(values ...*models.TxLabel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a transactionManyToManyLabelsTx) Replace(values ...*models.TxLabel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a transactionManyToManyLabelsTx) Delete(values ...*models.TxLabel) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a transactionManyToManyLabelsTx) Clear() error {
	return a.tx.Clear()
}

func (a transactionManyToManyLabelsTx) Count() int64 {
	return a.tx.Count()
}

func (a transactionManyToManyLabelsTx) Unscoped() *transactionManyToManyLabelsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type transactionDo struct{ gen.DO }

type ITransactionDo interface {
	gen.SubQuery
	Debug() ITransactionDo
	WithContext(ctx context.Context) ITransactionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITransactionDo
	WriteDB() ITransactionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITransactionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITransactionDo
	Not(conds ...gen.Condition) ITransactionDo
	Or(conds ...gen.Condition) ITransactionDo
	Select(conds ...field.Expr) ITransactionDo
	Where(conds ...gen.Condition) ITransactionDo
	Order(conds ...field.Expr) ITransactionDo
	Distinct(cols ...field.Expr) ITransactionDo
	Omit(cols ...field.Expr) ITransactionDo
	Join(table schema.Tabler, on ...field.Expr) ITransactionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITransactionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITransactionDo
	Group(cols ...field.Expr) ITransactionDo
	Having(conds ...gen.Condition) ITransactionDo
	Limit(limit int) ITransactionDo
	Offset(offset int) ITransactionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITransactionDo
	Unscoped() ITransactionDo
	Create(values ...*models.Transaction) error
	CreateInBatches(values []*models.Transaction, batchSize int) error
	Save(values ...*models.Transaction) error
	First() (*models.Transaction, error)
	Take() (*models.Transaction, error)
	Last() (*models.Transaction, error)
	Find() ([]*models.Transaction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Transaction, err error)
	FindInBatches(result *[]*models.Transaction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Transaction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITransactionDo
	Assign(attrs ...field.AssignExpr) ITransactionDo
	Joins(fields ...field.RelationField) ITransactionDo
	Preload(fields ...field.RelationField) ITransactionDo
	FirstOrInit() (*models.Transaction, error)
	FirstOrCreate() (*models.Transaction, error)
	FindByPage(offset int, limit int) (result []*models.Transaction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITransactionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t transactionDo) Debug() ITransactionDo {
	return t.withDO(t.DO.Debug())
}

func (t transactionDo) WithContext(ctx context.Context) ITransactionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t transactionDo) ReadDB() ITransactionDo {
	return t.Clauses(dbresolver.Read)
}

func (t transactionDo) WriteDB() ITransactionDo {
	return t.Clauses(dbresolver.Write)
}

func (t transactionDo) Session(config *gorm.Session) ITransactionDo {
	return t.withDO(t.DO.Session(config))
}

func (t transactionDo) Clauses(conds ...clause.Expression) ITransactionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t transactionDo) Returning(value interface{}, columns ...string) ITransactionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t transactionDo) Not(conds ...gen.Condition) ITransactionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t transactionDo) Or(conds ...gen.Condition) ITransactionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t transactionDo) Select(conds ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t transactionDo) Where(conds ...gen.Condition) ITransactionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t transactionDo) Order(conds ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t transactionDo) Distinct(cols ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t transactionDo) Omit(cols ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t transactionDo) Join(table schema.Tabler, on ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t transactionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t transactionDo) RightJoin(table schema.Tabler, on ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t transactionDo) Group(cols ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t transactionDo) Having(conds ...gen.Condition) ITransactionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t transactionDo) Limit(limit int) ITransactionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t transactionDo) Offset(offset int) ITransactionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t transactionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITransactionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t transactionDo) Unscoped() ITransactionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t transactionDo) Create(values ...*models.Transaction) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t transactionDo) CreateInBatches(values []*models.Transaction, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t transactionDo) Save(values ...*models.Transaction) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t transactionDo) First() (*models.Transaction, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Transaction), nil
	}
}

func (t transactionDo) Take() (*models.Transaction, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Transaction), nil
	}
}

func (t transactionDo) Last() (*models.Transaction, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Transaction), nil
	}
}

func (t transactionDo) Find() ([]*models.Transaction, error) {
	result, err := t.DO.Find()
	return result.([]*models.Transaction), err
}

func (t transactionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Transaction, err error) {
	buf := make([]*models.Transaction, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t transactionDo) FindInBatches(result *[]*models.Transaction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t transactionDo) Attrs(attrs ...field.AssignExpr) ITransactionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t transactionDo) Assign(attrs ...field.AssignExpr) ITransactionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t transactionDo) Joins(fields ...field.RelationField) ITransactionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t transactionDo) Preload(fields ...field.RelationField) ITransactionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t transactionDo) FirstOrInit() (*models.Transaction, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Transaction), nil
	}
}

func (t transactionDo) FirstOrCreate() (*models.Transaction, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Transaction), nil
	}
}

func (t transactionDo) FindByPage(offset int, limit int) (result []*models.Transaction, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t transactionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t transactionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t transactionDo) Delete(models ...*models.Transaction) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *transactionDo) withDO(do gen.Dao) *transactionDo {
	t.DO = *do.(*gen.DO)
	return t
}
