// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package genquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bsv-blockchain/go-wallet-toolbox/pkg/internal/storage/database/models"
)

func newTxLabelsMap(db *gorm.DB, opts ...gen.DOOption) txLabelsMap {
	_txLabelsMap := txLabelsMap{}

	_txLabelsMap.txLabelsMapDo.UseDB(db, opts...)
	_txLabelsMap.txLabelsMapDo.UseModel(&models.TxLabelsMap{})

	tableName := _txLabelsMap.txLabelsMapDo.TableName()
	_txLabelsMap.ALL = field.NewAsterisk(tableName)
	_txLabelsMap.CreatedAt = field.NewTime(tableName, "created_at")
	_txLabelsMap.UpdatedAt = field.NewTime(tableName, "updated_at")
	_txLabelsMap.TxLabelID = field.NewInt(tableName, "txLabelId")
	_txLabelsMap.TransactionID = field.NewInt(tableName, "transactionId")
	_txLabelsMap.IsDeleted = field.NewBool(tableName, "isDeleted")

	_txLabelsMap.fillFieldMap()

	return _txLabelsMap
}

type txLabelsMap struct {
	txLabelsMapDo

	ALL           field.Asterisk
	CreatedAt     field.Time
	UpdatedAt     field.Time
	TxLabelID     field.Int
	TransactionID field.Int
	IsDeleted     field.Bool

	fieldMap map[string]field.Expr
}

func (t txLabelsMap) Table(newTableName string) *txLabelsMap {
	t.txLabelsMapDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t txLabelsMap) As(alias string) *txLabelsMap {
	t.txLabelsMapDo.DO = *(t.txLabelsMapDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *txLabelsMap) updateTableName(table string) *txLabelsMap {
	t.ALL = field.NewAsterisk(table)
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.TxLabelID = field.NewInt(table, "txLabelId")
	t.TransactionID = field.NewInt(table, "transactionId")
	t.IsDeleted = field.NewBool(table, "isDeleted")

	t.fillFieldMap()

	return t
}

func (t *txLabelsMap) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *txLabelsMap) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["txLabelId"] = t.TxLabelID
	t.fieldMap["transactionId"] = t.TransactionID
	t.fieldMap["isDeleted"] = t.IsDeleted
}

func (t txLabelsMap) clone(db *gorm.DB) txLabelsMap {
	t.txLabelsMapDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t txLabelsMap) replaceDB(db *gorm.DB) txLabelsMap {
	t.txLabelsMapDo.ReplaceDB(db)
	return t
}

type txLabelsMapDo struct{ gen.DO }

type ITxLabelsMapDo interface {
	gen.SubQuery
	Debug() ITxLabelsMapDo
	WithContext(ctx context.Context) ITxLabelsMapDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITxLabelsMapDo
	WriteDB() ITxLabelsMapDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITxLabelsMapDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITxLabelsMapDo
	Not(conds ...gen.Condition) ITxLabelsMapDo
	Or(conds ...gen.Condition) ITxLabelsMapDo
	Select(conds ...field.Expr) ITxLabelsMapDo
	Where(conds ...gen.Condition) ITxLabelsMapDo
	Order(conds ...field.Expr) ITxLabelsMapDo
	Distinct(cols ...field.Expr) ITxLabelsMapDo
	Omit(cols ...field.Expr) ITxLabelsMapDo
	Join(table schema.Tabler, on ...field.Expr) ITxLabelsMapDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITxLabelsMapDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITxLabelsMapDo
	Group(cols ...field.Expr) ITxLabelsMapDo
	Having(conds ...gen.Condition) ITxLabelsMapDo
	Limit(limit int) ITxLabelsMapDo
	Offset(offset int) ITxLabelsMapDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITxLabelsMapDo
	Unscoped() ITxLabelsMapDo
	Create(values ...*models.TxLabelsMap) error
	CreateInBatches(values []*models.TxLabelsMap, batchSize int) error
	Save(values ...*models.TxLabelsMap) error
	First() (*models.TxLabelsMap, error)
	Take() (*models.TxLabelsMap, error)
	Last() (*models.TxLabelsMap, error)
	Find() ([]*models.TxLabelsMap, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TxLabelsMap, err error)
	FindInBatches(result *[]*models.TxLabelsMap, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.TxLabelsMap) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITxLabelsMapDo
	Assign(attrs ...field.AssignExpr) ITxLabelsMapDo
	Joins(fields ...field.RelationField) ITxLabelsMapDo
	Preload(fields ...field.RelationField) ITxLabelsMapDo
	FirstOrInit() (*models.TxLabelsMap, error)
	FirstOrCreate() (*models.TxLabelsMap, error)
	FindByPage(offset int, limit int) (result []*models.TxLabelsMap, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITxLabelsMapDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t txLabelsMapDo) Debug() ITxLabelsMapDo {
	return t.withDO(t.DO.Debug())
}

func (t txLabelsMapDo) WithContext(ctx context.Context) ITxLabelsMapDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t txLabelsMapDo) ReadDB() ITxLabelsMapDo {
	return t.Clauses(dbresolver.Read)
}

func (t txLabelsMapDo) WriteDB() ITxLabelsMapDo {
	return t.Clauses(dbresolver.Write)
}

func (t txLabelsMapDo) Session(config *gorm.Session) ITxLabelsMapDo {
	return t.withDO(t.DO.Session(config))
}

func (t txLabelsMapDo) Clauses(conds ...clause.Expression) ITxLabelsMapDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t txLabelsMapDo) Returning(value interface{}, columns ...string) ITxLabelsMapDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t txLabelsMapDo) Not(conds ...gen.Condition) ITxLabelsMapDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t txLabelsMapDo) Or(conds ...gen.Condition) ITxLabelsMapDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t txLabelsMapDo) Select(conds ...field.Expr) ITxLabelsMapDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t txLabelsMapDo) Where(conds ...gen.Condition) ITxLabelsMapDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t txLabelsMapDo) Order(conds ...field.Expr) ITxLabelsMapDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t txLabelsMapDo) Distinct(cols ...field.Expr) ITxLabelsMapDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t txLabelsMapDo) Omit(cols ...field.Expr) ITxLabelsMapDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t txLabelsMapDo) Join(table schema.Tabler, on ...field.Expr) ITxLabelsMapDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t txLabelsMapDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITxLabelsMapDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t txLabelsMapDo) RightJoin(table schema.Tabler, on ...field.Expr) ITxLabelsMapDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t txLabelsMapDo) Group(cols ...field.Expr) ITxLabelsMapDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t txLabelsMapDo) Having(conds ...gen.Condition) ITxLabelsMapDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t txLabelsMapDo) Limit(limit int) ITxLabelsMapDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t txLabelsMapDo) Offset(offset int) ITxLabelsMapDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t txLabelsMapDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITxLabelsMapDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t txLabelsMapDo) Unscoped() ITxLabelsMapDo {
	return t.withDO(t.DO.Unscoped())
}

func (t txLabelsMapDo) Create(values ...*models.TxLabelsMap) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t txLabelsMapDo) CreateInBatches(values []*models.TxLabelsMap, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t txLabelsMapDo) Save(values ...*models.TxLabelsMap) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t txLabelsMapDo) First() (*models.TxLabelsMap, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.TxLabelsMap), nil
	}
}

func (t txLabelsMapDo) Take() (*models.TxLabelsMap, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.TxLabelsMap), nil
	}
}

func (t txLabelsMapDo) Last() (*models.TxLabelsMap, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.TxLabelsMap), nil
	}
}

func (t txLabelsMapDo) Find() ([]*models.TxLabelsMap, error) {
	result, err := t.DO.Find()
	return result.([]*models.TxLabelsMap), err
}

func (t txLabelsMapDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TxLabelsMap, err error) {
	buf := make([]*models.TxLabelsMap, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t txLabelsMapDo) FindInBatches(result *[]*models.TxLabelsMap, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t txLabelsMapDo) Attrs(attrs ...field.AssignExpr) ITxLabelsMapDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t txLabelsMapDo) Assign(attrs ...field.AssignExpr) ITxLabelsMapDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t txLabelsMapDo) Joins(fields ...field.RelationField) ITxLabelsMapDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t txLabelsMapDo) Preload(fields ...field.RelationField) ITxLabelsMapDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t txLabelsMapDo) FirstOrInit() (*models.TxLabelsMap, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.TxLabelsMap), nil
	}
}

func (t txLabelsMapDo) FirstOrCreate() (*models.TxLabelsMap, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.TxLabelsMap), nil
	}
}

func (t txLabelsMapDo) FindByPage(offset int, limit int) (result []*models.TxLabelsMap, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t txLabelsMapDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t txLabelsMapDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t txLabelsMapDo) Delete(models ...*models.TxLabelsMap) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *txLabelsMapDo) withDO(do gen.Dao) *txLabelsMapDo {
	t.DO = *do.(*gen.DO)
	return t
}
