// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package genquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/bsv-blockchain/go-wallet-toolbox/pkg/internal/storage/database/models"
)

func newTxLabel(db *gorm.DB, opts ...gen.DOOption) txLabel {
	_txLabel := txLabel{}

	_txLabel.txLabelDo.UseDB(db, opts...)
	_txLabel.txLabelDo.UseModel(&models.TxLabel{})

	tableName := _txLabel.txLabelDo.TableName()
	_txLabel.ALL = field.NewAsterisk(tableName)
	_txLabel.CreatedAt = field.NewTime(tableName, "created_at")
	_txLabel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_txLabel.TxLabelID = field.NewUint(tableName, "txLabelId")
	_txLabel.Label = field.NewString(tableName, "label")
	_txLabel.UserID = field.NewInt(tableName, "userId")
	_txLabel.IsDeleted = field.NewBool(tableName, "isDeleted")
	_txLabel.Transactions = txLabelManyToManyTransactions{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Transactions", "models.Transaction"),
		Commission: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Transactions.Commission", "models.Commission"),
		},
		ProvenTx: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Transactions.ProvenTx", "models.ProvenTx"),
		},
		Outputs: struct {
			field.RelationField
			SpentByTransaction struct {
				field.RelationField
			}
			Basket struct {
				field.RelationField
			}
			Transaction struct {
				field.RelationField
			}
			Tags struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Transactions.Outputs", "models.Output"),
			SpentByTransaction: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Transactions.Outputs.SpentByTransaction", "models.Transaction"),
			},
			Basket: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Transactions.Outputs.Basket", "models.OutputBasket"),
			},
			Transaction: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Transactions.Outputs.Transaction", "models.Transaction"),
			},
			Tags: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Transactions.Outputs.Tags", "models.OutputTag"),
			},
		},
		Inputs: struct {
			field.RelationField
			SpentByTransaction struct {
				field.RelationField
			}
			Basket struct {
				field.RelationField
			}
			Transaction struct {
				field.RelationField
			}
			Tags struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Transactions.Inputs", "models.Output"),
			SpentByTransaction: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Transactions.Inputs.SpentByTransaction", "models.Transaction"),
			},
			Basket: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Transactions.Inputs.Basket", "models.OutputBasket"),
			},
			Transaction: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Transactions.Inputs.Transaction", "models.Transaction"),
			},
			Tags: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Transactions.Inputs.Tags", "models.OutputTag"),
			},
		},
		Labels: struct {
			field.RelationField
			Transactions struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Transactions.Labels", "models.TxLabel"),
			Transactions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Transactions.Labels.Transactions", "models.Transaction"),
			},
		},
	}

	_txLabel.fillFieldMap()

	return _txLabel
}

type txLabel struct {
	txLabelDo

	ALL          field.Asterisk
	CreatedAt    field.Time
	UpdatedAt    field.Time
	TxLabelID    field.Uint
	Label        field.String
	UserID       field.Int
	IsDeleted    field.Bool
	Transactions txLabelManyToManyTransactions

	fieldMap map[string]field.Expr
}

func (t txLabel) Table(newTableName string) *txLabel {
	t.txLabelDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t txLabel) As(alias string) *txLabel {
	t.txLabelDo.DO = *(t.txLabelDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *txLabel) updateTableName(table string) *txLabel {
	t.ALL = field.NewAsterisk(table)
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.TxLabelID = field.NewUint(table, "txLabelId")
	t.Label = field.NewString(table, "label")
	t.UserID = field.NewInt(table, "userId")
	t.IsDeleted = field.NewBool(table, "isDeleted")

	t.fillFieldMap()

	return t
}

func (t *txLabel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *txLabel) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["txLabelId"] = t.TxLabelID
	t.fieldMap["label"] = t.Label
	t.fieldMap["userId"] = t.UserID
	t.fieldMap["isDeleted"] = t.IsDeleted

}

func (t txLabel) clone(db *gorm.DB) txLabel {
	t.txLabelDo.ReplaceConnPool(db.Statement.ConnPool)
	t.Transactions.db = db.Session(&gorm.Session{Initialized: true})
	t.Transactions.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t txLabel) replaceDB(db *gorm.DB) txLabel {
	t.txLabelDo.ReplaceDB(db)
	t.Transactions.db = db.Session(&gorm.Session{})
	return t
}

type txLabelManyToManyTransactions struct {
	db *gorm.DB

	field.RelationField

	Commission struct {
		field.RelationField
	}
	ProvenTx struct {
		field.RelationField
	}
	Outputs struct {
		field.RelationField
		SpentByTransaction struct {
			field.RelationField
		}
		Basket struct {
			field.RelationField
		}
		Transaction struct {
			field.RelationField
		}
		Tags struct {
			field.RelationField
		}
	}
	Inputs struct {
		field.RelationField
		SpentByTransaction struct {
			field.RelationField
		}
		Basket struct {
			field.RelationField
		}
		Transaction struct {
			field.RelationField
		}
		Tags struct {
			field.RelationField
		}
	}
	Labels struct {
		field.RelationField
		Transactions struct {
			field.RelationField
		}
	}
}

func (a txLabelManyToManyTransactions) Where(conds ...field.Expr) *txLabelManyToManyTransactions {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a txLabelManyToManyTransactions) WithContext(ctx context.Context) *txLabelManyToManyTransactions {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a txLabelManyToManyTransactions) Session(session *gorm.Session) *txLabelManyToManyTransactions {
	a.db = a.db.Session(session)
	return &a
}

func (a txLabelManyToManyTransactions) Model(m *models.TxLabel) *txLabelManyToManyTransactionsTx {
	return &txLabelManyToManyTransactionsTx{a.db.Model(m).Association(a.Name())}
}

func (a txLabelManyToManyTransactions) Unscoped() *txLabelManyToManyTransactions {
	a.db = a.db.Unscoped()
	return &a
}

type txLabelManyToManyTransactionsTx struct{ tx *gorm.Association }

func (a txLabelManyToManyTransactionsTx) Find() (result []*models.Transaction, err error) {
	return result, a.tx.Find(&result)
}

func (a txLabelManyToManyTransactionsTx) Append(values ...*models.Transaction) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a txLabelManyToManyTransactionsTx) Replace(values ...*models.Transaction) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a txLabelManyToManyTransactionsTx) Delete(values ...*models.Transaction) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a txLabelManyToManyTransactionsTx) Clear() error {
	return a.tx.Clear()
}

func (a txLabelManyToManyTransactionsTx) Count() int64 {
	return a.tx.Count()
}

func (a txLabelManyToManyTransactionsTx) Unscoped() *txLabelManyToManyTransactionsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type txLabelDo struct{ gen.DO }

type ITxLabelDo interface {
	gen.SubQuery
	Debug() ITxLabelDo
	WithContext(ctx context.Context) ITxLabelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITxLabelDo
	WriteDB() ITxLabelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITxLabelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITxLabelDo
	Not(conds ...gen.Condition) ITxLabelDo
	Or(conds ...gen.Condition) ITxLabelDo
	Select(conds ...field.Expr) ITxLabelDo
	Where(conds ...gen.Condition) ITxLabelDo
	Order(conds ...field.Expr) ITxLabelDo
	Distinct(cols ...field.Expr) ITxLabelDo
	Omit(cols ...field.Expr) ITxLabelDo
	Join(table schema.Tabler, on ...field.Expr) ITxLabelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITxLabelDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITxLabelDo
	Group(cols ...field.Expr) ITxLabelDo
	Having(conds ...gen.Condition) ITxLabelDo
	Limit(limit int) ITxLabelDo
	Offset(offset int) ITxLabelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITxLabelDo
	Unscoped() ITxLabelDo
	Create(values ...*models.TxLabel) error
	CreateInBatches(values []*models.TxLabel, batchSize int) error
	Save(values ...*models.TxLabel) error
	First() (*models.TxLabel, error)
	Take() (*models.TxLabel, error)
	Last() (*models.TxLabel, error)
	Find() ([]*models.TxLabel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TxLabel, err error)
	FindInBatches(result *[]*models.TxLabel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.TxLabel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITxLabelDo
	Assign(attrs ...field.AssignExpr) ITxLabelDo
	Joins(fields ...field.RelationField) ITxLabelDo
	Preload(fields ...field.RelationField) ITxLabelDo
	FirstOrInit() (*models.TxLabel, error)
	FirstOrCreate() (*models.TxLabel, error)
	FindByPage(offset int, limit int) (result []*models.TxLabel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITxLabelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t txLabelDo) Debug() ITxLabelDo {
	return t.withDO(t.DO.Debug())
}

func (t txLabelDo) WithContext(ctx context.Context) ITxLabelDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t txLabelDo) ReadDB() ITxLabelDo {
	return t.Clauses(dbresolver.Read)
}

func (t txLabelDo) WriteDB() ITxLabelDo {
	return t.Clauses(dbresolver.Write)
}

func (t txLabelDo) Session(config *gorm.Session) ITxLabelDo {
	return t.withDO(t.DO.Session(config))
}

func (t txLabelDo) Clauses(conds ...clause.Expression) ITxLabelDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t txLabelDo) Returning(value interface{}, columns ...string) ITxLabelDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t txLabelDo) Not(conds ...gen.Condition) ITxLabelDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t txLabelDo) Or(conds ...gen.Condition) ITxLabelDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t txLabelDo) Select(conds ...field.Expr) ITxLabelDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t txLabelDo) Where(conds ...gen.Condition) ITxLabelDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t txLabelDo) Order(conds ...field.Expr) ITxLabelDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t txLabelDo) Distinct(cols ...field.Expr) ITxLabelDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t txLabelDo) Omit(cols ...field.Expr) ITxLabelDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t txLabelDo) Join(table schema.Tabler, on ...field.Expr) ITxLabelDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t txLabelDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITxLabelDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t txLabelDo) RightJoin(table schema.Tabler, on ...field.Expr) ITxLabelDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t txLabelDo) Group(cols ...field.Expr) ITxLabelDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t txLabelDo) Having(conds ...gen.Condition) ITxLabelDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t txLabelDo) Limit(limit int) ITxLabelDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t txLabelDo) Offset(offset int) ITxLabelDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t txLabelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITxLabelDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t txLabelDo) Unscoped() ITxLabelDo {
	return t.withDO(t.DO.Unscoped())
}

func (t txLabelDo) Create(values ...*models.TxLabel) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t txLabelDo) CreateInBatches(values []*models.TxLabel, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t txLabelDo) Save(values ...*models.TxLabel) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t txLabelDo) First() (*models.TxLabel, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.TxLabel), nil
	}
}

func (t txLabelDo) Take() (*models.TxLabel, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.TxLabel), nil
	}
}

func (t txLabelDo) Last() (*models.TxLabel, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.TxLabel), nil
	}
}

func (t txLabelDo) Find() ([]*models.TxLabel, error) {
	result, err := t.DO.Find()
	return result.([]*models.TxLabel), err
}

func (t txLabelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TxLabel, err error) {
	buf := make([]*models.TxLabel, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t txLabelDo) FindInBatches(result *[]*models.TxLabel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t txLabelDo) Attrs(attrs ...field.AssignExpr) ITxLabelDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t txLabelDo) Assign(attrs ...field.AssignExpr) ITxLabelDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t txLabelDo) Joins(fields ...field.RelationField) ITxLabelDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t txLabelDo) Preload(fields ...field.RelationField) ITxLabelDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t txLabelDo) FirstOrInit() (*models.TxLabel, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.TxLabel), nil
	}
}

func (t txLabelDo) FirstOrCreate() (*models.TxLabel, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.TxLabel), nil
	}
}

func (t txLabelDo) FindByPage(offset int, limit int) (result []*models.TxLabel, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t txLabelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t txLabelDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t txLabelDo) Delete(models ...*models.TxLabel) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *txLabelDo) withDO(do gen.Dao) *txLabelDo {
	t.DO = *do.(*gen.DO)
	return t
}
