// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bsv-blockchain/go-wallet-toolbox/pkg/wdk (interfaces: WalletStorageProvider)
//
// Generated by this command:
//
//	mockgen -destination=../internal/mocks/mock_wallet_storage_writer.go -package=mocks github.com/bsv-blockchain/go-wallet-toolbox/pkg/wdk WalletStorageProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	wdk "github.com/bsv-blockchain/go-wallet-toolbox/pkg/wdk"
	gomock "go.uber.org/mock/gomock"
)

// MockWalletStorageProvider is a mock of WalletStorageProvider interface.
type MockWalletStorageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWalletStorageProviderMockRecorder
	isgomock struct{}
}

// MockWalletStorageProviderMockRecorder is the mock recorder for MockWalletStorageProvider.
type MockWalletStorageProviderMockRecorder struct {
	mock *MockWalletStorageProvider
}

// NewMockWalletStorageProvider creates a new mock instance.
func NewMockWalletStorageProvider(ctrl *gomock.Controller) *MockWalletStorageProvider {
	mock := &MockWalletStorageProvider{ctrl: ctrl}
	mock.recorder = &MockWalletStorageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletStorageProvider) EXPECT() *MockWalletStorageProviderMockRecorder {
	return m.recorder
}

// AbortAction mocks base method.
func (m *MockWalletStorageProvider) AbortAction(ctx context.Context, auth wdk.AuthID, args wdk.AbortActionArgs) (*wdk.AbortActionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortAction", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.AbortActionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AbortAction indicates an expected call of AbortAction.
func (mr *MockWalletStorageProviderMockRecorder) AbortAction(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortAction", reflect.TypeOf((*MockWalletStorageProvider)(nil).AbortAction), ctx, auth, args)
}

// CreateAction mocks base method.
func (m *MockWalletStorageProvider) CreateAction(ctx context.Context, auth wdk.AuthID, args wdk.ValidCreateActionArgs) (*wdk.StorageCreateActionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAction", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.StorageCreateActionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAction indicates an expected call of CreateAction.
func (mr *MockWalletStorageProviderMockRecorder) CreateAction(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAction", reflect.TypeOf((*MockWalletStorageProvider)(nil).CreateAction), ctx, auth, args)
}

// FindOrInsertSyncStateAuth mocks base method.
func (m *MockWalletStorageProvider) FindOrInsertSyncStateAuth(ctx context.Context, auth wdk.AuthID, storageIdentityKey, storageName string) (*wdk.FindOrInsertSyncStateAuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrInsertSyncStateAuth", ctx, auth, storageIdentityKey, storageName)
	ret0, _ := ret[0].(*wdk.FindOrInsertSyncStateAuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrInsertSyncStateAuth indicates an expected call of FindOrInsertSyncStateAuth.
func (mr *MockWalletStorageProviderMockRecorder) FindOrInsertSyncStateAuth(ctx, auth, storageIdentityKey, storageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrInsertSyncStateAuth", reflect.TypeOf((*MockWalletStorageProvider)(nil).FindOrInsertSyncStateAuth), ctx, auth, storageIdentityKey, storageName)
}

// FindOrInsertUser mocks base method.
func (m *MockWalletStorageProvider) FindOrInsertUser(ctx context.Context, identityKey string) (*wdk.FindOrInsertUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrInsertUser", ctx, identityKey)
	ret0, _ := ret[0].(*wdk.FindOrInsertUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrInsertUser indicates an expected call of FindOrInsertUser.
func (mr *MockWalletStorageProviderMockRecorder) FindOrInsertUser(ctx, identityKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrInsertUser", reflect.TypeOf((*MockWalletStorageProvider)(nil).FindOrInsertUser), ctx, identityKey)
}

// FindOutputBasketsAuth mocks base method.
func (m *MockWalletStorageProvider) FindOutputBasketsAuth(ctx context.Context, auth wdk.AuthID, filters wdk.FindOutputBasketsArgs) (wdk.TableOutputBaskets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOutputBasketsAuth", ctx, auth, filters)
	ret0, _ := ret[0].(wdk.TableOutputBaskets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOutputBasketsAuth indicates an expected call of FindOutputBasketsAuth.
func (mr *MockWalletStorageProviderMockRecorder) FindOutputBasketsAuth(ctx, auth, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOutputBasketsAuth", reflect.TypeOf((*MockWalletStorageProvider)(nil).FindOutputBasketsAuth), ctx, auth, filters)
}

// FindOutputsAuth mocks base method.
func (m *MockWalletStorageProvider) FindOutputsAuth(ctx context.Context, auth wdk.AuthID, filters wdk.FindOutputsArgs) (wdk.TableOutputs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOutputsAuth", ctx, auth, filters)
	ret0, _ := ret[0].(wdk.TableOutputs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOutputsAuth indicates an expected call of FindOutputsAuth.
func (mr *MockWalletStorageProviderMockRecorder) FindOutputsAuth(ctx, auth, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOutputsAuth", reflect.TypeOf((*MockWalletStorageProvider)(nil).FindOutputsAuth), ctx, auth, filters)
}

// GetSyncChunk mocks base method.
func (m *MockWalletStorageProvider) GetSyncChunk(ctx context.Context, args wdk.RequestSyncChunkArgs) (*wdk.SyncChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncChunk", ctx, args)
	ret0, _ := ret[0].(*wdk.SyncChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncChunk indicates an expected call of GetSyncChunk.
func (mr *MockWalletStorageProviderMockRecorder) GetSyncChunk(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncChunk", reflect.TypeOf((*MockWalletStorageProvider)(nil).GetSyncChunk), ctx, args)
}

// InsertCertificateAuth mocks base method.
func (m *MockWalletStorageProvider) InsertCertificateAuth(ctx context.Context, auth wdk.AuthID, certificate *wdk.TableCertificateX) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCertificateAuth", ctx, auth, certificate)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCertificateAuth indicates an expected call of InsertCertificateAuth.
func (mr *MockWalletStorageProviderMockRecorder) InsertCertificateAuth(ctx, auth, certificate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCertificateAuth", reflect.TypeOf((*MockWalletStorageProvider)(nil).InsertCertificateAuth), ctx, auth, certificate)
}

// InternalizeAction mocks base method.
func (m *MockWalletStorageProvider) InternalizeAction(ctx context.Context, auth wdk.AuthID, args wdk.InternalizeActionArgs) (*wdk.InternalizeActionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalizeAction", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.InternalizeActionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalizeAction indicates an expected call of InternalizeAction.
func (mr *MockWalletStorageProviderMockRecorder) InternalizeAction(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalizeAction", reflect.TypeOf((*MockWalletStorageProvider)(nil).InternalizeAction), ctx, auth, args)
}

// ListActions mocks base method.
func (m *MockWalletStorageProvider) ListActions(ctx context.Context, auth wdk.AuthID, args wdk.ListActionsArgs) (*wdk.ListActionsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActions", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.ListActionsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActions indicates an expected call of ListActions.
func (mr *MockWalletStorageProviderMockRecorder) ListActions(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActions", reflect.TypeOf((*MockWalletStorageProvider)(nil).ListActions), ctx, auth, args)
}

// ListCertificates mocks base method.
func (m *MockWalletStorageProvider) ListCertificates(ctx context.Context, auth wdk.AuthID, args wdk.ListCertificatesArgs) (*wdk.ListCertificatesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCertificates", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.ListCertificatesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCertificates indicates an expected call of ListCertificates.
func (mr *MockWalletStorageProviderMockRecorder) ListCertificates(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCertificates", reflect.TypeOf((*MockWalletStorageProvider)(nil).ListCertificates), ctx, auth, args)
}

// ListOutputs mocks base method.
func (m *MockWalletStorageProvider) ListOutputs(ctx context.Context, auth wdk.AuthID, args wdk.ListOutputsArgs) (*wdk.ListOutputsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOutputs", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.ListOutputsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOutputs indicates an expected call of ListOutputs.
func (mr *MockWalletStorageProviderMockRecorder) ListOutputs(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOutputs", reflect.TypeOf((*MockWalletStorageProvider)(nil).ListOutputs), ctx, auth, args)
}

// ListTransactions mocks base method.
func (m *MockWalletStorageProvider) ListTransactions(ctx context.Context, auth wdk.AuthID, args wdk.ListTransactionsArgs) (*wdk.ListTransactionsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.ListTransactionsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockWalletStorageProviderMockRecorder) ListTransactions(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockWalletStorageProvider)(nil).ListTransactions), ctx, auth, args)
}

// MakeAvailable mocks base method.
func (m *MockWalletStorageProvider) MakeAvailable(ctx context.Context) (*wdk.TableSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeAvailable", ctx)
	ret0, _ := ret[0].(*wdk.TableSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeAvailable indicates an expected call of MakeAvailable.
func (mr *MockWalletStorageProviderMockRecorder) MakeAvailable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeAvailable", reflect.TypeOf((*MockWalletStorageProvider)(nil).MakeAvailable), ctx)
}

// Migrate mocks base method.
func (m *MockWalletStorageProvider) Migrate(ctx context.Context, storageName, storageIdentityKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx, storageName, storageIdentityKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Migrate indicates an expected call of Migrate.
func (mr *MockWalletStorageProviderMockRecorder) Migrate(ctx, storageName, storageIdentityKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockWalletStorageProvider)(nil).Migrate), ctx, storageName, storageIdentityKey)
}

// ProcessAction mocks base method.
func (m *MockWalletStorageProvider) ProcessAction(ctx context.Context, auth wdk.AuthID, args wdk.ProcessActionArgs) (*wdk.ProcessActionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessAction", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.ProcessActionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessAction indicates an expected call of ProcessAction.
func (mr *MockWalletStorageProviderMockRecorder) ProcessAction(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessAction", reflect.TypeOf((*MockWalletStorageProvider)(nil).ProcessAction), ctx, auth, args)
}

// ProcessSyncChunk mocks base method.
func (m *MockWalletStorageProvider) ProcessSyncChunk(ctx context.Context, args wdk.RequestSyncChunkArgs, chunk *wdk.SyncChunk) (*wdk.ProcessSyncChunkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessSyncChunk", ctx, args, chunk)
	ret0, _ := ret[0].(*wdk.ProcessSyncChunkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessSyncChunk indicates an expected call of ProcessSyncChunk.
func (mr *MockWalletStorageProviderMockRecorder) ProcessSyncChunk(ctx, args, chunk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSyncChunk", reflect.TypeOf((*MockWalletStorageProvider)(nil).ProcessSyncChunk), ctx, args, chunk)
}

// RelinquishCertificate mocks base method.
func (m *MockWalletStorageProvider) RelinquishCertificate(ctx context.Context, auth wdk.AuthID, args wdk.RelinquishCertificateArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelinquishCertificate", ctx, auth, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// RelinquishCertificate indicates an expected call of RelinquishCertificate.
func (mr *MockWalletStorageProviderMockRecorder) RelinquishCertificate(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelinquishCertificate", reflect.TypeOf((*MockWalletStorageProvider)(nil).RelinquishCertificate), ctx, auth, args)
}

// RelinquishOutput mocks base method.
func (m *MockWalletStorageProvider) RelinquishOutput(ctx context.Context, auth wdk.AuthID, args wdk.RelinquishOutputArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelinquishOutput", ctx, auth, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// RelinquishOutput indicates an expected call of RelinquishOutput.
func (mr *MockWalletStorageProviderMockRecorder) RelinquishOutput(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelinquishOutput", reflect.TypeOf((*MockWalletStorageProvider)(nil).RelinquishOutput), ctx, auth, args)
}

// SetActive mocks base method.
func (m *MockWalletStorageProvider) SetActive(ctx context.Context, auth wdk.AuthID, newActiveStorageIdentityKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, auth, newActiveStorageIdentityKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockWalletStorageProviderMockRecorder) SetActive(ctx, auth, newActiveStorageIdentityKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockWalletStorageProvider)(nil).SetActive), ctx, auth, newActiveStorageIdentityKey)
}
