// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/4chain-ag/go-wallet-toolbox/pkg/wdk (interfaces: WalletStorageProvider)
//
// Generated by this command:
//
//	mockgen -destination=../internal/mocks/mock_wallet_storage_writer.go -package=mocks github.com/4chain-ag/go-wallet-toolbox/pkg/wdk WalletStorageProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	wdk "github.com/4chain-ag/go-wallet-toolbox/pkg/wdk"
	gomock "go.uber.org/mock/gomock"
)

// MockWalletStorageProvider is a mock of WalletStorageProvider interface.
type MockWalletStorageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWalletStorageProviderMockRecorder
	isgomock struct{}
}

// MockWalletStorageProviderMockRecorder is the mock recorder for MockWalletStorageProvider.
type MockWalletStorageProviderMockRecorder struct {
	mock *MockWalletStorageProvider
}

// NewMockWalletStorageProvider creates a new mock instance.
func NewMockWalletStorageProvider(ctrl *gomock.Controller) *MockWalletStorageProvider {
	mock := &MockWalletStorageProvider{ctrl: ctrl}
	mock.recorder = &MockWalletStorageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletStorageProvider) EXPECT() *MockWalletStorageProviderMockRecorder {
	return m.recorder
}

// CreateAction mocks base method.
func (m *MockWalletStorageProvider) CreateAction(ctx context.Context, auth wdk.AuthID, args wdk.ValidCreateActionArgs) (*wdk.StorageCreateActionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAction", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.StorageCreateActionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAction indicates an expected call of CreateAction.
func (mr *MockWalletStorageProviderMockRecorder) CreateAction(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAction", reflect.TypeOf((*MockWalletStorageProvider)(nil).CreateAction), ctx, auth, args)
}

// FindOrInsertUser mocks base method.
func (m *MockWalletStorageProvider) FindOrInsertUser(ctx context.Context, identityKey string) (*wdk.FindOrInsertUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrInsertUser", ctx, identityKey)
	ret0, _ := ret[0].(*wdk.FindOrInsertUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrInsertUser indicates an expected call of FindOrInsertUser.
func (mr *MockWalletStorageProviderMockRecorder) FindOrInsertUser(ctx, identityKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrInsertUser", reflect.TypeOf((*MockWalletStorageProvider)(nil).FindOrInsertUser), ctx, identityKey)
}

// InsertCertificateAuth mocks base method.
func (m *MockWalletStorageProvider) InsertCertificateAuth(ctx context.Context, auth wdk.AuthID, certificate *wdk.TableCertificateX) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCertificateAuth", ctx, auth, certificate)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCertificateAuth indicates an expected call of InsertCertificateAuth.
func (mr *MockWalletStorageProviderMockRecorder) InsertCertificateAuth(ctx, auth, certificate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCertificateAuth", reflect.TypeOf((*MockWalletStorageProvider)(nil).InsertCertificateAuth), ctx, auth, certificate)
}

// InternalizeAction mocks base method.
func (m *MockWalletStorageProvider) InternalizeAction(ctx context.Context, auth wdk.AuthID, args wdk.InternalizeActionArgs) (*wdk.InternalizeActionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalizeAction", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.InternalizeActionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InternalizeAction indicates an expected call of InternalizeAction.
func (mr *MockWalletStorageProviderMockRecorder) InternalizeAction(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalizeAction", reflect.TypeOf((*MockWalletStorageProvider)(nil).InternalizeAction), ctx, auth, args)
}

// ListActions mocks base method.
func (m *MockWalletStorageProvider) ListActions(ctx context.Context, auth wdk.AuthID, args wdk.ListActionsArgs) (*wdk.ListActionsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActions", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.ListActionsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActions indicates an expected call of ListActions.
func (mr *MockWalletStorageProviderMockRecorder) ListActions(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActions", reflect.TypeOf((*MockWalletStorageProvider)(nil).ListActions), ctx, auth, args)
}

// ListCertificates mocks base method.
func (m *MockWalletStorageProvider) ListCertificates(ctx context.Context, auth wdk.AuthID, args wdk.ListCertificatesArgs) (*wdk.ListCertificatesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCertificates", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.ListCertificatesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCertificates indicates an expected call of ListCertificates.
func (mr *MockWalletStorageProviderMockRecorder) ListCertificates(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCertificates", reflect.TypeOf((*MockWalletStorageProvider)(nil).ListCertificates), ctx, auth, args)
}

// ListOutputs mocks base method.
func (m *MockWalletStorageProvider) ListOutputs(ctx context.Context, auth wdk.AuthID, args wdk.ListOutputsArgs) (*wdk.ListOutputsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOutputs", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.ListOutputsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOutputs indicates an expected call of ListOutputs.
func (mr *MockWalletStorageProviderMockRecorder) ListOutputs(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOutputs", reflect.TypeOf((*MockWalletStorageProvider)(nil).ListOutputs), ctx, auth, args)
}

// MakeAvailable mocks base method.
func (m *MockWalletStorageProvider) MakeAvailable(ctx context.Context) (*wdk.TableSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeAvailable", ctx)
	ret0, _ := ret[0].(*wdk.TableSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeAvailable indicates an expected call of MakeAvailable.
func (mr *MockWalletStorageProviderMockRecorder) MakeAvailable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeAvailable", reflect.TypeOf((*MockWalletStorageProvider)(nil).MakeAvailable), ctx)
}

// Migrate mocks base method.
func (m *MockWalletStorageProvider) Migrate(ctx context.Context, storageName, storageIdentityKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx, storageName, storageIdentityKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Migrate indicates an expected call of Migrate.
func (mr *MockWalletStorageProviderMockRecorder) Migrate(ctx, storageName, storageIdentityKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockWalletStorageProvider)(nil).Migrate), ctx, storageName, storageIdentityKey)
}

// ProcessAction mocks base method.
func (m *MockWalletStorageProvider) ProcessAction(ctx context.Context, auth wdk.AuthID, args wdk.ProcessActionArgs) (*wdk.ProcessActionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessAction", ctx, auth, args)
	ret0, _ := ret[0].(*wdk.ProcessActionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessAction indicates an expected call of ProcessAction.
func (mr *MockWalletStorageProviderMockRecorder) ProcessAction(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessAction", reflect.TypeOf((*MockWalletStorageProvider)(nil).ProcessAction), ctx, auth, args)
}

// RelinquishCertificate mocks base method.
func (m *MockWalletStorageProvider) RelinquishCertificate(ctx context.Context, auth wdk.AuthID, args wdk.RelinquishCertificateArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelinquishCertificate", ctx, auth, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// RelinquishCertificate indicates an expected call of RelinquishCertificate.
func (mr *MockWalletStorageProviderMockRecorder) RelinquishCertificate(ctx, auth, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelinquishCertificate", reflect.TypeOf((*MockWalletStorageProvider)(nil).RelinquishCertificate), ctx, auth, args)
}
