// Code generated by gorm-names-gen. DO NOT EDIT.
// Generated at: Mon, 07 Jul 2025 14:47:33 CEST
//
// To regenerate this file, run "go generate" in the models directory.

package models

var TagColumnNames = struct {
	CreatedAt string
	UpdatedAt string
	DeletedAt string
	Name      string
	UserID    string
}{
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	Name:      "name",
	UserID:    "user_id",
}

var SettingColumnNames = struct {
	CreatedAt          string
	UpdatedAt          string
	StorageIdentityKey string
	StorageName        string
	Chain              string
	MaxOutputScript    string
}{
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
	StorageIdentityKey: "storage_identity_key",
	StorageName:        "storage_name",
	Chain:              "chain",
	MaxOutputScript:    "max_output_script",
}

var CertificateColumnNames = struct {
	ID                 string
	CreatedAt          string
	UpdatedAt          string
	DeletedAt          string
	Type               string
	SerialNumber       string
	Certifier          string
	Subject            string
	Verifier           string
	RevocationOutpoint string
	Signature          string
	UserID             string
}{
	ID:                 "id",
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
	DeletedAt:          "deleted_at",
	Type:               "type",
	SerialNumber:       "serial_number",
	Certifier:          "certifier",
	Subject:            "subject",
	Verifier:           "verifier",
	RevocationOutpoint: "revocation_outpoint",
	Signature:          "signature",
	UserID:             "user_id",
}

var UserUTXOColumnNames = struct {
	UserID             string
	OutputID           string
	BasketName         string
	Satoshis           string
	EstimatedInputSize string
	CreatedAt          string
	ReservedByID       string
}{
	UserID:             "user_id",
	OutputID:           "output_id",
	BasketName:         "basket_name",
	Satoshis:           "satoshis",
	EstimatedInputSize: "estimated_input_size",
	CreatedAt:          "created_at",
	ReservedByID:       "reserved_by_id",
}

var KnownTxColumnNames = struct {
	CreatedAt   string
	UpdatedAt   string
	TxID        string
	Status      string
	Attempts    string
	Notified    string
	RawTx       string
	InputBeef   string
	History     string
	BlockHeight string
	MerklePath  string
	MerkleRoot  string
	BlockHash   string
}{
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	TxID:        "tx_id",
	Status:      "status",
	Attempts:    "attempts",
	Notified:    "notified",
	RawTx:       "raw_tx",
	InputBeef:   "input_beef",
	History:     "history",
	BlockHeight: "block_height",
	MerklePath:  "merkle_path",
	MerkleRoot:  "merkle_root",
	BlockHash:   "block_hash",
}

var OutputColumnNames = struct {
	ID                 string
	CreatedAt          string
	UpdatedAt          string
	DeletedAt          string
	UserID             string
	TransactionID      string
	SpentBy            string
	Vout               string
	Satoshis           string
	LockingScript      string
	CustomInstructions string
	DerivationPrefix   string
	DerivationSuffix   string
	BasketName         string
	Spendable          string
	Change             string
	Description        string
	ProvidedBy         string
	Purpose            string
	Type               string
	SenderIdentityKey  string
}{
	ID:                 "id",
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
	DeletedAt:          "deleted_at",
	UserID:             "user_id",
	TransactionID:      "transaction_id",
	SpentBy:            "spent_by",
	Vout:               "vout",
	Satoshis:           "satoshis",
	LockingScript:      "locking_script",
	CustomInstructions: "custom_instructions",
	DerivationPrefix:   "derivation_prefix",
	DerivationSuffix:   "derivation_suffix",
	BasketName:         "basket_name",
	Spendable:          "spendable",
	Change:             "change",
	Description:        "description",
	ProvidedBy:         "provided_by",
	Purpose:            "purpose",
	Type:               "type",
	SenderIdentityKey:  "sender_identity_key",
}

var TransactionLabelsColumnNames = struct {
	TransactionID string
	LabelName     string
	LabelUserID   string
}{
	TransactionID: "transaction_id",
	LabelName:     "label_name",
	LabelUserID:   "label_user_id",
}

var SyncStateColumnNames = struct {
	ID                 string
	CreatedAt          string
	UpdatedAt          string
	DeletedAt          string
	UserID             string
	StorageIdentityKey string
	StorageName        string
	Status             string
	RefNum             string
	SyncMap            string
	When               string
	Satoshis           string
}{
	ID:                 "id",
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
	DeletedAt:          "deleted_at",
	UserID:             "user_id",
	StorageIdentityKey: "storage_identity_key",
	StorageName:        "storage_name",
	Status:             "status",
	RefNum:             "ref_num",
	SyncMap:            "sync_map",
	When:               "when",
	Satoshis:           "satoshis",
}

var OutputTagsColumnNames = struct {
	OutputID  string
	TagName   string
	TagUserID string
}{
	OutputID:  "output_id",
	TagName:   "tag_name",
	TagUserID: "tag_user_id",
}

var CommissionColumnNames = struct {
	ID            string
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     string
	UserID        string
	TransactionID string
	Satoshis      string
	KeyOffset     string
	IsRedeemed    string
	LockingScript string
}{
	ID:            "id",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	DeletedAt:     "deleted_at",
	UserID:        "user_id",
	TransactionID: "transaction_id",
	Satoshis:      "satoshis",
	KeyOffset:     "key_offset",
	IsRedeemed:    "is_redeemed",
	LockingScript: "locking_script",
}

var OutputBasketColumnNames = struct {
	CreatedAt               string
	UpdatedAt               string
	DeletedAt               string
	Name                    string
	UserID                  string
	NumberOfDesiredUTXOs    string
	MinimumDesiredUTXOValue string
}{
	CreatedAt:               "created_at",
	UpdatedAt:               "updated_at",
	DeletedAt:               "deleted_at",
	Name:                    "name",
	UserID:                  "user_id",
	NumberOfDesiredUTXOs:    "number_of_desired_utxos",
	MinimumDesiredUTXOValue: "minimum_desired_utxo_value",
}

var LabelColumnNames = struct {
	CreatedAt string
	UpdatedAt string
	DeletedAt string
	Name      string
	UserID    string
}{
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	Name:      "name",
	UserID:    "user_id",
}

var KeyValueColumnNames = struct {
	CreatedAt string
	UpdatedAt string
	Key       string
	Value     string
}{
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	Key:       "key",
	Value:     "value",
}

var UserColumnNames = struct {
	CreatedAt     string
	UpdatedAt     string
	UserID        string
	IdentityKey   string
	ActiveStorage string
}{
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	UserID:        "user_id",
	IdentityKey:   "identity_key",
	ActiveStorage: "active_storage",
}

var CertificateFieldColumnNames = struct {
	CreatedAt     string
	UpdatedAt     string
	FieldName     string
	FieldValue    string
	MasterKey     string
	UserID        string
	CertificateID string
}{
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	FieldName:     "field_name",
	FieldValue:    "field_value",
	MasterKey:     "master_key",
	UserID:        "user_id",
	CertificateID: "certificate_id",
}

var TransactionColumnNames = struct {
	ID          string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   string
	UserID      string
	Status      string
	Reference   string
	IsOutgoing  string
	Satoshis    string
	Description string
	Version     string
	LockTime    string
	TxID        string
	InputBeef   string
}{
	ID:          "id",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
	UserID:      "user_id",
	Status:      "status",
	Reference:   "reference",
	IsOutgoing:  "is_outgoing",
	Satoshis:    "satoshis",
	Description: "description",
	Version:     "version",
	LockTime:    "lock_time",
	TxID:        "tx_id",
	InputBeef:   "input_beef",
}

var NumericIDLookupColumnNames = struct {
	NumID     string
	TableName string
	StringID  string
}{
	NumID:     "num_id",
	TableName: "table_name",
	StringID:  "string_id",
}
