name: "On pull request"

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - opened

permissions:
  pull-requests: write

jobs:
  on-pr:
    uses: 4chain-ag/workflows/.github/workflows/on-pull-request.yml@main
